### ISSUE TITLE
TS dislikes Win 64-bit release.

### ISSUE THREAD

**Issue by Icecream-burglar** [pathmann/pyTSon#1]
![capture](https://cloud.githubusercontent.com/assets/18321968/17990098/5da9413a-6af8-11e6-83fe-8dcc373fe7e9.png)

Teamspeak is up to date. I downloaded the latest release of pyTSon. It's not happy.
New to the TS3 plugin scene, so I might just be doing something stupid. But I can't get it to work.

P.S. I'm on Win10 64-bit.

**Comment by pathmann** [comment]
Did you move the python lib to your ts3 client install directory?

So from "%APPDATA%/TSClient/plugins/pyTSon/python35.dll" to something like "C:\Program Files\TeamSpeak 3 Client"

**Comment by Icecream-burglar** [comment]
Aah, I looked for a way to change to a "beta" channel for ts, but couldn't find it. So I assumed my ts was up to date. I guess there's a separate download for an "unstable" build of ts? At any rate, I did try to use an older version of pyTSon after the latest failed, but I may have not gone far enough back. I'll try to the link you gave me.

**Comment by Icecream-burglar** [comment]
K, so the link you gave me also fails. Strangely though, the 'API Version' box is filled out with '252622832'.

**Comment by pathmann** [comment]
Sorry, I can't reproduce this in my Windows VM.

I don't know if that shown API Version is random, some error code or anything else, but that's normal, if some dependencies of a plugin could not be fulfilled.

The only dependency I can imagine, is the python library. Is there a python35.dll in your TeamSpeak 3 client install directory? So next to the client binary, the Qt libraries, etc.

**Comment by Icecream-burglar** [comment]
That was it. Python wasn't where TS could find it. It was so dumb of me. I guess I assumed TS could find the python install already on my pc :).

**Comment by Icecream-burglar** [comment]
Thanks for the help!

Next up, fighting with an x86 processor emulator on the raspberrypi to get ts3 client installed there. Going to make a bot ;).

**Comment by pathmann** [comment]
I'm glad it works now.
I guess, I should add a README at least for windows, where manually moving the lib is necessary.

Good luck with your bot.
