### ISSUE TITLE
.......

### ISSUE THREAD

**Issue by ImScopy** [pathmann/pyTSon#101]
i try out to make a script and i fail
if you please please do it for me 
i will do anything for you it so important to me 
i can do a shoutout on my yt channel 500 sub :(
or pay money i just need on client join channel move him to another channel automatically that it 
please dont ignore me i need your help be helpful and i swear i will do tutorials on your scripts

**Comment by pathmann** [comment]
Not gonna happen.
If you are not familiar with python or can't (or don't want to) dive in, pyTSon might not be a plugin for you.

You might find someone else or a repository with scripts you need to subscribe to.
