### ISSUE TITLE
Read requirements.txt from script folders

### ISSUE THREAD

**Issue by Bluscream** [pathmann/pyTSon#103]
I thought it would be a nice addition to the requirements field in a repo if pyTSon would auto install packages that are written inside a `requirements.txt` when a plugin is loaded for the first time. (https://pip.readthedocs.io/en/1.1/requirements.html)

**Comment by pathmann** [comment]
Those requirements can be set in the repository: https://github.com/pathmann/pyTSon_repository/blob/master/README.md#json-format
