### ISSUE TITLE
Call stop() method of console autorun script on close

### ISSUE THREAD

**Issue by Bluscream** [pathmann/pyTSon#106]
It would be neat if before closing the pytson console stop() will be called if it exists

**Comment by pathmann** [comment]
That's not the intention of the autorun feature. It's meant to do imports etc, not start long running tasks or such. 

Simply calling a method if it exists does not feel clean.
You can connect to signals of the console window.

**Comment by Bluscream** [comment]
Do i have to find the widget in .AllWidgets() or does the autorunscript provide it?

**Comment by pathmann** [comment]
The file is simply read in and evaluated: https://github.com/pathmann/pyTSon/blob/master/ressources/python/pytsonui/console.py#L87

The cleanest solution would be, if the context locals would be "destroyed" when the console is closed.

**Comment by pathmann** [comment]
3af3f64 will remove locals created in the console.
