### ISSUE TITLE
MultiSelect Move incompatible with Dark Themes

### ISSUE THREAD

**Issue by exp111** [pathmann/pyTSon#107]
Channel & Client Names are black. Spacers are white though.

**Comment by pathmann** [comment]
Not sure if this belongs here.

1. Multiselect move is a plugin, but the base treeview is indeed.
2. My guess is, that it's more or less an issue of the theme (if the view is styled, but the child items are not in a consistent way, it looks like a theme issue). So any plugin using a QTreeView will have this problem. 

As long as you don't provide any link to the theme, nobody can say for sure.

**Comment by exp111** [comment]
Using [DarkenTS](https://www.myteamspeak.com/addons/686209af-0b66-4805-b2d7-0e990f7cb9e0). 
The Font color gets set like this:
`QTreeView::item:selected:active,
QTreeView::item:selected:!active {
  background-color: rgb(62,79,94);
  color: rgb(216,216,216);
}` and
`QWidget {																																				
  font-family: "Segoe UI", Arial, sans-serif;
  color: rgb(216,216,216);
}`

The ServerView Rows are probably not QWidgets

**Comment by pathmann** [comment]
That's how it looks in my client with DarkenTS.

![multiselectmove_darkents](https://user-images.githubusercontent.com/3155203/44620528-491d0700-a896-11e8-8e4d-18a80d698a77.png)

I see what you mean, but I'm not that experienced with CSS/Stylesheets and don't know, why the Stylesheet is not applied to it.
