### ISSUE TITLE
Can't use functions of PyTSon

### ISSUE THREAD

**Issue by Dejvis96** [pathmann/pyTSon#110]
I have (I think) such casual question-problem, since I am pretty new to this addon.
Why all of those scripts are grayed out? I have top grade permissions on the server btw.
![seyf](https://user-images.githubusercontent.com/24878593/49611303-67b89100-f9a1-11e8-8af7-b0ce695ff816.png)

**Comment by pathmann** [comment]
Because you didn't enable the plugins in the settings?

**Comment by Dejvis96** [comment]
> Because you didn't enable the plugins in the settings?

Sure I did.... obviously.
