### ISSUE TITLE
User joined the channel which i am currently in?

### ISSUE THREAD

**Issue by pipje2001** [pathmann/pyTSon#115]
Is it possible to run a function when someone joined the channel which i am in? onClientMoveEvent only works on myself. And is there a function which runs when someone starts talking? I tried searching for these function but i couldn't find them

**Comment by pathmann** [comment]
[OnClientMoveEvent ](https://pytson.4qt.de/ts3plugin.ts3plugin-class.html#onClientMoveEvent) is invoked for every client in view. But keep in mind, that there are other callbacks which could be triggered instead, like onClientMoveMovedEvent (if another client moved the client around) . 
If someone starts or stops talking, [onTalkStatusChangeEvent](https://pytson.4qt.de/ts3plugin.ts3plugin-class.html#onTalkStatusChangeEvent)  is invoked.

**Comment by pipje2001** [comment]
I see, onClientMoveMovedEvent doesn't seem to work though, and is it possible to import a different module? i would like to use request (https://stackabuse.com/the-python-requests-module/) but when i try to import it the script dissapears from the plugins list in pyTSon settings

**Comment by pathmann** [comment]
This works form me:
```python
import ts3lib
from ts3plugin import ts3plugin
class movetest(ts3plugin):
  requestAutoload = False 
  name = "movetest" 
  version = "1.0" 
  apiVersion = 21 
  author = "I" 
  description = "asd" 
  offersConfigure = False 
  commandKeyword = "asd" 
  infoTitle = "" 
  menuItems = [] 
  hotkeys = []

  def onClientMoveMovedEvent(self, schid, cl, ochan, nchan, vis, moverid, movername, moveruid, movemsg):
    ts3lib.printMessageToCurrentTab("client id %s got moved by %s" % (cl, movername))

def moveEvent(self, schid, cl, ochan, nchan, vis, movemsg):
  ts3lib.printMessageToCurrentTab("client id %s moved" % cl)

movetest.onClientMoveEvent = moveEvent
```

(I copied & pasted from my console, that's the reason for the monkey patching at the end)
