### ISSUE TITLE
sys.stdin Runtime error

### ISSUE THREAD

**Issue by lukshan13** [pathmann/pyTSon#116]
When ever I try to have an input() in my python script, and I run it straight from the console, I get a lost sys.stdin error. Any idea why?

**Comment by pathmann** [comment]
Pytsons console is some kind of emulated, so you will read from stdin, but your console input does not go to stdin.
You should call your function with parameters.

**Comment by pathmann** [comment]
Another possibility would be to wrap your user input to some qt gui widgets created with pythonqt.

**Comment by lukshan13** [comment]
Hi, thanks for getting back so quickly! Yeah, I figured the best way to do it was to wrap it in a function and call that function with parameters, and it seems to work. I'm not sure how to use pythonqt so i'll look in to that. Thanks again!
