### ISSUE TITLE
onDisplayNameChanged Evenet Friends/Foe Status?

### ISSUE THREAD

**Issue by DerLuemmel** [pathmann/pyTSon#117]
onDisplayNameChanged is called when someone changed his display name OR if you add a client to your contacts. (friend / foe )

My problem is that if i check the contact status in settings.db for the client which i added for ex. to my bloked list, then it returned not the current status. Is there some kind of delay?

Or is there a other way to keep track of theese actions?

**Comment by pathmann** [comment]
To be clear, onDisplayNameChanged is triggered, because the client changes the contacts nickname to something like "[blocked]xxx".

I don't know, when the client updates the contact status in its database, so there might be "a delay".

Reading the settings database is not really supported by the plugin sdk, so you shouldn't depend on it.

Might be helpfull to know, what you are trying to achieve, there could be another callback which fits better for your needs.

**Comment by DerLuemmel** [comment]
I need a way to react when the contact status changed for my [Contact Manager Project](https://github.com/DerLuemmel/ContactManager)

So actions like "kick from channel" will triggerd not only when a blocked user joins the client channel but also when the client changes a users contact status in the channel to blocked.

**Comment by Bluscream** [comment]
Maybe you can subscribe to a qt event for a treewidget that tells you wether a client has become green, red or white?

**Comment by pathmann** [comment]
You could check if [onUpdateClientEvent](https://pytson.4qt.de/ts3plugin.ts3plugin-class.html#onUpdateClientEvent) is triggered after the contact status is changed in the settings database.

**Comment by DerLuemmel** [comment]
> You could check if onUpdateClientEvent is triggered after the contact status is changed in the settings database.

onUpdateClientEvent does not trigger

> Maybe you can subscribe to a qt event for a treewidget that tells you wether a client has become green, red or white?

Puh, TreeView has no signals for this.

**Comment by pathmann** [comment]
If you wanna go with some hack into the treeview, you have to look into the model instead.

**Comment by DerLuemmel** [comment]
`self.tree= self.getWidgetByObjectName("ServerTreeView").model()
 self.tree.dataChanged.connect(self.doSomething)`

doSomething does not trigger. Any idea?

I know that you are not responsible for this problem, but would be awesome if we get it to work.

**Comment by DerLuemmel** [comment]
Now i did a workarround with QTimer for the delay.
```
def onClientDisplayNameChanged(self, schid, clientID, displayName, uid):        
        QTimer.singleShot(200, lambda : self.doContactActions(schid, clientID))
```

**Comment by Bluscream** [comment]
Nice to know a way to use parameters with a QTimer (https://stackoverflow.com/questions/48924190/any-way-to-identify-which-qtimer-was-called)
