### ISSUE TITLE
ts3.requestClientKickFromChannel returns 0 even if it should

### ISSUE THREAD

**Issue by DerLuemmel** [pathmann/pyTSon#118]
error = ts3lib.requestClientKickFromChannel(...)

error is always 0 even if the client has no rights to perform the kick action.

same with requestSetClientChannelGroup()

**Comment by Bluscream** [comment]
You need to use [`ts3lib.createReturnCode()`](https://pytson.4qt.de/ts3lib-module.html#createReturnCode) and [`onServerErrorEvent`](https://pytson.4qt.de/ts3plugin.ts3plugin-class.html#onServerErrorEvent) / `onServerPermissionErrorEvent`](https://pytson.4qt.de/ts3plugin.ts3plugin-class.html#onServerPermissionErrorEvent)

**Comment by DerLuemmel** [comment]
so. i create a global var
and with onServerPermissionErrorEvent i check for the returncode and set my global var?

i will try it

**Comment by Bluscream** [comment]
yes, best to create a list in case something doesn't arrive before the next

**Comment by DerLuemmel** [comment]
cant follow you with the list ^^

**Comment by Bluscream** [comment]
returncodes = []
def whereineedthem():
    ret = ts3lib.createReturnCode()
    returncodes.add(ret)
    Bla(id, ret)

def onerror(ret):
   if not ret in returncodes: return
   returncodes.remove(ret)

**Comment by DerLuemmel** [comment]
sneaky
