### ISSUE TITLE
How to add plugin to Teamspeak ?

### ISSUE THREAD

**Issue by Arthur-crbr** [pathmann/pyTSon#127]
Teamspeak told us that the plugin using API 21 or it expects 23. I download the plugin on their website but it's the same. How can I do ?
Thanks

**Comment by Arthur-crbr** [comment]
And were I have to put the folder of pyTSon ?

**Comment by pathmann** [comment]
I don't have the time to update builds of this plugin, so you have to build it yourselve with the correct toolchain (TS3 client's qt version + msvc compiler).
