### ISSUE TITLE
[Bug] Fix Github wiki

### ISSUE THREAD

**Issue by Bluscream** [pathmann/pyTSon#13]
The wiki button is just redirecting to the repo :(

**Comment by pathmann** [comment]
don't have the time to manage a wiki. I don't see that much people using pyTSon, so currently no need for this I guess.

**Comment by Bluscream** [comment]
PyTSon is simply very unknown. None of the devs/scripters of TS3 tools that i talked to since 3.1 knew about it.

**Comment by Bluscream** [comment]
Btw. IMO the example plugins should be in the wiki with explanation/docs instead of their own useless repo :)

**Comment by pathmann** [comment]
I don't feel the need to compete with other plugins :)

**Comment by Bluscream** [comment]
@pathmann Why don't you just create a small wiki entry / markdown file to document only the functions you added like `pytsonui.getValues` and `pytsonui.setupUI`...

To attract more possible scripters i would even add hard to find useful pythonqt functions like `QMessageBox.*` and `QInputDialog.*`. This is very useful stuff that took years to find atleast for me.

**Comment by pathmann** [comment]
The functions in the pytsonui module will be added to pyTSon's docs.

QMessageBox and QInputDialog are not more useful than other classes in the Qt framework. 
I see, that it's hard, if you don't know Qt. But I don't plan to copy the Qt docs (which are great btw.).
So the Qt docs, [the pythonqt docs](http://pythonqt.sourceforge.net/Developer.html) and [pytson.4qt.de](pyTSon's docs) should be good to go.
