### ISSUE TITLE
[Script][No Bug] Crash with `widgetinfo.py` when joining server.

### ISSUE THREAD

**Issue by Bluscream** [pathmann/pyTSon#15]
When joining a server when having your new script `widgetinfo.py` in my scripts dir my client crashes.

![image](https://cloud.githubusercontent.com/assets/3318223/19834053/83ef9ba6-9e50-11e6-8d7d-83c849b363a8.png)

```
  Problemereignisname:  BEX64
  Anwendungsname:   ts3client_win64.exe
  Anwendungsversion:    3.1.0.0
  Anwendungszeitstempel:    5805cd71
  Fehlermodulname:  ucrtbase.DLL
  Fehlermodulversion:   10.0.10586.9
  Fehlermodulzeitstempel:   5642c48d
  Ausnahmeoffset:   00000000000698fe
  Ausnahmecode: c0000409
  Ausnahmedaten:    0000000000000007
  Betriebsystemversion: 6.3.9600.2.0.0.768.101
  Gebietsschema-ID: 1031
  Zusatzinformation 1:  60cf
  Zusatzinformation 2:  60cf3fc2ba0a148d4b3eb4901bb7e56c
  Zusatzinformation 3:  30bd
  Zusatzinformation 4:  30bd53f46639182e03da2e5fc2cd36c4

Lesen Sie unsere Datenschutzbestimmungen online:
  http://go.microsoft.com/fwlink/?linkid=280262

Wenn die Onlinedatenschutzbestimmungen nicht verfügbar sind, lesen Sie unsere Datenschutzbestimmungen offline:
  C:\WINDOWS\system32\de-DE\erofflps.txt
```

> Maybe the crash occurs cause your newest commit to pyTSon isn't pushed as release ?

**Comment by Bluscream** [comment]
Since it's trying to import the new `QAbstractItemModel` i guess the reason is what i quoted so i'm going to close this :)

**Comment by pathmann** [comment]
Not necessarily. I only registered quintptr as metatype, QAbstractItemModel is wrapped since the beginning.

So the only change, the qMetaTypeRegister should bring, is that calling QAbstractItemModel::createIndex won't throw an exception when using an internalId.

But to retest, you need to compile pyTSon yourselve or wait for the next release which will include that change.

**Comment by Bluscream** [comment]
Since i have no freakin idea how to compile something except using Visual Studio, i'll wait :P

**Comment by Bluscream** [comment]
I got this kinda fixed but #17 sneaked in my house then :o :x

**Comment by pathmann** [comment]
How did you fix it? If some python script code crashes pyTSon resp. the ts3 client, this is a bug.

**Comment by Bluscream** [comment]
I simply replaced all files that i can replace without compiling from the source ^^ pregen/* etc.
