### ISSUE TITLE
[Bug][Script] widgetInfo not working 

### ISSUE THREAD

**Issue by Bluscream** [pathmann/pyTSon#18]
```python
31.10.2016 04:54:01	pyTSon	Error	Calling onHotkeyEvent failed with error "Error calling method
Traceback (most recent call last):
  File "C:/Users/blusc_000/AppData/Roaming/TS3Client/plugins/pyTSon/scripts\ts3plugin.py", line 210, in callMethod
    return meth(*args)
  File "C:/Users/blusc_000/AppData/Roaming/TS3Client/plugins/pyTSon/scripts\ts3plugin.py", line 320, in onHotkeyEvent
    plugin.onHotkeyEvent(lockey)
  File "C:/Users/blusc_000/AppData/Roaming/TS3Client/plugins/pyTSon/scripts\widgetinfo.py", line 296, in onHotkeyEvent
    self.showInfo(QApplication.instance().widgetAt(QCursor.pos()))
  File "C:/Users/blusc_000/AppData/Roaming/TS3Client/plugins/pyTSon/scripts\widgetinfo.py", line 288, in showInfo
    self.dlg.setWidget(widg)
  File "C:/Users/blusc_000/AppData/Roaming/TS3Client/plugins/pyTSon/scripts\widgetinfo.py", line 216, in setWidget
    index = self.treemodel.createIndex(node.row, 0, node.id)
ValueError: Could not find matching overload for given arguments:
(0, 0, 2462)
 The following slots are available:
createIndex(int row, int column, quintptr id) -> QModelIndex
createIndex(int row, int column, void data) -> QModelIndex
createIndex(int row, int column) -> QModelIndex
```

![image](https://cloud.githubusercontent.com/assets/3318223/19844614/bc0975dc-9f2e-11e6-81db-387188696e66.png)

**Comment by pathmann** [comment]
No bug, you just have to wait for the next release.

See my comment [here](https://github.com/pathmann/pyTSon/issues/15#issuecomment-257149072).

**Comment by Bluscream** [comment]
Can you leave a compiled win64 dll here for me? :3

**Comment by pathmann** [comment]
I'll start my vm cycle tonight, so there will be a new release tomorrow.

**Comment by Bluscream** [comment]
Oh, so you need every platform as VM to compile it for these? Or are the VM's just for runtime testing?

**Comment by pathmann** [comment]
3 vms + my workstation. 


BTW. The Widgetinfo script is crappy as hell (the model and it's method to work with the underlying data is broken), so don't rely on it.

**Comment by Bluscream** [comment]
I thought i could figure out how to manipulate the channel tree with it for example :(

**Comment by pathmann** [comment]
The goal of the script is to look into the ui structure of the client. 

As for the tree: we talked about it, without replacing the model or setting some proxy- resp. filter-model, this won't work.

**Comment by Bluscream** [comment]
I hoped the tree was just some kind of List/TableWidget :D

**Comment by pathmann** [comment]
Nope, it's a QTreeView.

**Comment by Bluscream** [comment]
Wait there is a `virtual void rowsInserted(const QModelIndex & parent, int start, int end)` function but no `insertRow()` function :/

**Comment by pathmann** [comment]
http://doc.qt.io/qt-4.8/modelview.html

The view only displays the data. The rowsInserted slot is called by the model.

**Comment by Bluscream** [comment]
So `void	insertTopLevelItem(int index, QTreeWidgetItem * item)` would be the best guess :D

**Comment by pathmann** [comment]
QTreeView != QTreeWidget! 

The model is the connecting layer between the real data and the view. 

So either manipulate the real data (not possible, I guess) or replace the model, which defines, how the data (and which data) will be abstracted.

**Comment by Bluscream** [comment]
Woow my current version of the script crashes teamspeak when opening the log window to review the stacktrace xD
