### ISSUE TITLE
[Bug][Windows] directory separators not working in 1.0.4 bundle on windows

### ISSUE THREAD

**Issue by Bluscream** [pathmann/pyTSon#20]
![image](https://cloud.githubusercontent.com/assets/3318223/19903319/7fd55e28-a06e-11e6-9d3c-5bb0d365ef14.png)

**Comment by Bluscream** [comment]
Oh yeah sorry my bad :D

**Comment by pathmann** [comment]
Fixed with 4abd831b7c36f8c7226671f81d624365628c88a1.
