### ISSUE TITLE
[Feature Request] Print to pyTSon console.

### ISSUE THREAD

**Issue by Bluscream** [pathmann/pyTSon#25]
I would like to have a function like
```python
pytsonui.print(message)
```

Simple and easy :)

**Comment by pathmann** [comment]
Already possible.

```python3
from ts3plugin import PluginHost
if PluginHost.shell:
  PluginHost.shell.appendLine("blub")
```

**Comment by Bluscream** [comment]
`wontfix`? More like `Already implemented` ;P

**Comment by Bluscream** [comment]
@pathmann Can i also open a shell within the scripts environment?

So i can use script internal functions or even follow script execution line by line?

**Comment by pathmann** [comment]
Can't see any restrictions ...

**Comment by Bluscream** [comment]
The console is seperate AFAIK. As you need to `import` everything you need yourself.

And i can't simply `import` scripts cause they're not in the path:
```python
['C:/Users/blusc_000/AppData/Roaming/TS3Client/plugins/pyTSon/scripts', 'C:/Users/blusc_000/AppData/Roaming/TS3Client/plugins/pyTSon/include', 'C:/Users/blusc_000/AppData/Roaming/TS3Client/plugins/pyTSon/include/Lib_win64', 'C:/Users/blusc_000/AppData/Roaming/TS3Client/plugins/pyTSon/include/Lib_win64/lib-dynload'
```

**Comment by Bluscream** [comment]
@pathmann Also i would request a `clear` or `clear()` function, cause the console is getting a little messy sometimes :P

**Comment by pathmann** [comment]
> The console is seperate AFAIK. As you need to import everything you need yourself.
>
> And i can't simply import scripts cause they're not in the path:

I don't get it. pytsonui.py is in include which is in sys.path. And if it wouldn't, you can always add it to sys.path.
