### ISSUE TITLE
[Feature Request] Make updateCheck available through the API

### ISSUE THREAD

**Issue by Bluscream** [pathmann/pyTSon#27]
Wouldn't it be better if you could use the `updateCheck()` function from any plugin?

I would change the syntax to:
```python
    @classmethod
    def updateCheck(cls, user, repo, callback=cls.updateCheckFinished):
        if cls.nwm: #there is a pending updatecheck
            return
        cls.nwm = QNetworkAccessManager()
            cls.nwm.connect("finished(QNetworkReply*)", callback)
        cls.nwm.get(QNetworkRequest(QUrl("https://api.github.com/repos/"+user+"/"+repo+"/releases/latest")))
```
So you could call
```python
import ts3plugin
ts3plugin.updateCheck("pathmann", "pyTSon", self.updateCheckFinished)
def updateCheckFinished(self, reply):
    ...
```
for example

Would be also nice to implement into https://github.com/pathmann/pyTSon/issues/13#issuecomment-259395997

**Comment by Bluscream** [comment]
It could be made more efficient for scripts of course by comparing file timestamps in the repo vs. local and auto-downloading and replacing outdated files, but that would be too much, even for you ♥

**Comment by pathmann** [comment]
> Of course it could be made more efficient for scripts of course by comparing file timestamps in the repo vs. local and auto-downloading and replacing outdated files, but that would be too much, even for you ♥

That's possible yes and indeed I thought about it, but that would always require a restart of the c plugin, which is not possible to request (to the ts3 client). Not restarting can crash things. So, this is really just a updateCHECK. In addition, if the current maximum filesize of the ts3 internal addons system is gone, pyTSon will be available there.

As for the rest: is it that hard to create your own NetworkAccessManager (or use the requests module)? Scripts that want to check for self updates on github should check the incoming data for themselves. I don't see, that the PluginHost should carry a NetworkManager around to receive requests for plugins. And then you can implement auto-updating your script.

Some global addon repository(ies) is on TODO, but has nothing to do with this updateCheck.

**Comment by Bluscream** [comment]
> Some global addon repository(ies) is on TODO

Do you mean something like https://github.com/IRDeNial/BD-Even-Better-Repo ?

If yes, it would be dope if devs could request to have their scripts added :)

**Comment by Bluscream** [comment]
> That's possible yes and indeed I thought about it, but that would always require a restart of the c plugin, which is not possible to request (to the ts3 client). Not restarting can crash things.

You could use platform dependent scripts (`batch` and `bash`) to
```batch
taskkill /f /im ts3client_win64.exe
ts3server://
exit
```
and then `QApplication.instance().quit()`

**Comment by pathmann** [comment]
Really? Or just no! That's evil, so we'll keep it like that.
