### ISSUE TITLE
verifyServerPassword

### ISSUE THREAD

**Issue by Bluscream** [pathmann/pyTSon#29]
Maybe this isn't a bug or it's just a bug in the SDK but the `ts3.verifyServerPassword` always returns `0` even when passing the password hash instead of the plain text pw (I'm testing with a temp pw, btw).

![image](https://cloud.githubusercontent.com/assets/3318223/20455393/686bbd68-ae5b-11e6-9c55-3da6c0b139d4.png)

<details>Why isn't there a `ts3.hashpassword(password)` function in the sdk :(</details>

**Comment by pathmann** [comment]
I'm not very familiar with that function in the plugin sdk, but as it has a returnCode parameter I guess, it works asynchronous, so you'll get a serverErrorEvent with the specific returnCode (if defined).

**Comment by Bluscream** [comment]
I'll try

**Comment by pathmann** [comment]
Confirmed, you have to pass a returnCode and can then get the result in onServerErrorEvent (with error in [ERROR_ok, ERROR_server_invalid_password] = [0, 1028]).
