### ISSUE TITLE
master version crashes on loading built-in GUI windows

### ISSUE THREAD

**Issue by allquixotic** [pathmann/pyTSon#30]
Using

 - macOS Sierra
 - pyTSon master = `c21a06ed3ecb586edaddebac0feaa0c6836fdaa2`
 - PythonQt patched-6 = `7f3f6a97a76f5d035fb52db1f9039adb56f35192`
 - Teamspeak 3.1 Beta (11/9/16 09:25:53 using Qt 5.6.1)
 - Qt Open Source 5.6.1 installed
 - Python 3.5.2 installed
 - `pip3.5 install` to get pycparser and jinja2
 - Xcode 7.3.1

I symlinked the python3.5 install into the original path pointed to in `python.pri`. Then I ran `qmake && make` and it succeeded with no errors. 

Then I ran `python3.5 tools/bundle.py /Users/me/Documents/pyTSon /Library/Frameworks/Python.framework/Versions/3.5 out mac`.

Then I double clicked the resulting `pyTSon_mac.ts3_plugin` and let it install.

However, whenever I try to load any of the pop-up windows of pyTSon (Settings, Console or Check for updates), I get the following message to stderr followed by TS3 crashing....

`QWidget: Must construct a QApplication before a QWidget`

Sounds like a possible code-up error in pyTSon?

**Comment by pathmann** [comment]
Sounds really like a version missmatch of Qt (in plugin and ts3 client).
The releases [here](https://github.com/pathmann/pyTSon/releases/tag/v1.0.4) do work?

**Comment by allquixotic** [comment]
Hi,

Yes, pyTSon 1.0.4 works fine. But I think there is an error in my plugin code in an event handler that is not getting printed anywhere, so I have no way of knowing what is wrong. I was hoping to build from git so that I could see exactly what the error message is, or maybe it'll be fixed, but it seems Qt 5.6.1 binaries I downloaded are not compatible...

I wonder if TS3 on Mac is a 32-bit binary (only) and Qt 5.6.1 is 64-bit only? That'd do it, right? But then again the plugin does register the plugin menu items successfully.

**Comment by pathmann** [comment]
The TS3 client on mac is 64-bit-only.
