### ISSUE TITLE
VoiceDataEvent callbacks never fire?

### ISSUE THREAD

**Issue by allquixotic** [pathmann/pyTSon#31]
The `onTextMessageEvent` works but the others don't. Using 1.0.4 w/ TS 3.1 Beta on OS X.

```
    def onTextMessageEvent(self, schid, targetMode, toID, fromID, fromName, fromUniqueIdentifier, message, ffIgnored):
        ts3.printMessageToCurrentTab(message)

    def onEditPostProcessVoiceDataEvent(schid, clientID, samples, channels, channelSpeakerArray, channelFillMask):
        ts3.printMessageToCurrentTab('onEditPostProcessVoiceDataEvent')

    def onEditMixedPlaybackVoiceDataEvent(schid, samples, channels, channelSpeakerArray, channelFillMask):
        ts3.printMessageToCurrentTab('onEditMixedPlaybackVoiceDataEvent')

    def onEditCapturedVoiceDataEvent(schid, samples, channels, edited):
        ts3.printMessageToCurrentTab('onEditCapturedVoiceDataEvent')

    def onEditPlaybackVoiceDataEvent(self, schid, clientID, samples, channels):
        ts3.printMessageToCurrentTab('onEditPlaybackVoiceDataEvent')
```

**Comment by Bluscream** [comment]
The onTextMessageEvent works fine for me, but AFAIK the others are buggy so they are commented out in the c code.

**Comment by allquixotic** [comment]
That's very unfortunate. What's "buggy" about them? I'll try to find the last version that was commented out and see if I can get it minimally working. I don't need to update the data, I just need to read it.

**Comment by allquixotic** [comment]
Ah, here we go: https://github.com/pathmann/pyTSon/blob/c21a06ed3ecb586edaddebac0feaa0c6836fdaa2/src/pythonhost.cpp#L609

That would be the problem.

**Comment by pathmann** [comment]
The voicedata callbacks are called in another thread by the client.

Unfortunately pyTSon has no multithreading support, so I cycled out every callback fired from other threads than the main thread.
