### ISSUE TITLE
[Possible Bug] Hotkeys overlapping eachother

### ISSUE THREAD

**Issue by Bluscream** [pathmann/pyTSon#33]
I created two different hotkeys in two different scripts and somehow they're overlapping eachother. Can someone double-check this?

**Comment by pathmann** [comment]
Minimal test code? What does overlapping mean?

**Comment by Bluscream** [comment]
Test Code:
- https://github.com/Bluscream/pyTSon_plugins/blob/master/scripts/devTools.py#L328
- https://github.com/Bluscream/pyTSon_plugins/blob/master/scripts/unlocker.py#L18

![image](https://cloud.githubusercontent.com/assets/3318223/20969024/70c19994-bc87-11e6-92f1-c6374fdec726.png)
It feels absolutely random what happens on each hotkey

**Comment by pathmann** [comment]
That's no real testcode!

Loaded this two plugins:
```python3
from ts3plugin import ts3plugin

import ts3

class firstplug(ts3plugin):
    requestAutoload = False
    name = "First"
    author = "Thomas \"PLuS\" Pathmann"
    description = "First test"
    version = "0.0.1"
    apiVersion = 21
    offersConfigure = False
    commandKeyword = ""
    infoTitle = None
    menuItems = []
    hotkeys = [("0", "Fist test")]

    def onHotkeyEvent(self, key):
        if key == "0":
            ts3.printMessageToCurrentTab("First hotkey")


class secondplug(ts3plugin):
    requestAutoload = False
    name = "Second"
    author = "Thomas \"PLuS\" Pathmann"
    description = "Second test"
    version = "0.0.1"
    apiVersion = 21
    offersConfigure = False
    commandKeyword = ""
    infoTitle = None
    menuItems = []
    hotkeys = [("0", "Second test")]

    def onHotkeyEvent(self, key):
        if key == "0":
            ts3.printMessageToCurrentTab("Second hotkey")
```

Then added two hotkeys in client, pressed them and received the message accordingly. So I can't reproduce this.

**Comment by Bluscream** [comment]
Which keys did you assign them to?

**Comment by pathmann** [comment]
F11 and F12.

**Comment by Bluscream** [comment]
Can you try it with the hotkeys i used?

**Comment by Bluscream** [comment]
If it still works then i'd guess we can close this.

**Comment by pathmann** [comment]
No, I can't. I guess "Zehnertastatur" is your numpad (so Numpad 8)? The ts3 client does not let me assign that keys here (on linux).

**Comment by Bluscream** [comment]
Damn, i wonder if there is someone else using your plugin on windows who could help in such cases.

Going to close this now and will reopen it if it occurs again in a different scenario

**Comment by pathmann** [comment]
I don't think, that it is connected to the key you are using.
But if so, it does not feel like a bug in pyTSon, because only the client handles the key, plugins only get the assigned keyword in the event.

**Comment by Bluscream** [comment]
Yeah but my thought was, since pyTSon collects all script hotkeys and passes them to teamspeak maybe it confuses multiple keys when they come back as event. Like the menuIDs.

**Comment by pathmann** [comment]
Possible, but unlikely that it is connected to the specific keys.

> Like the menuIDs
What's that supposed to mean? That's supposedly bugged too?

**Comment by Bluscream** [comment]
No, but the ts client expects one plugin per menuID

> (ts3defines.PluginMenuType.PLUGIN_MENU_TYPE_GLOBAL, `0`, "", "")

**Comment by pathmann** [comment]
Same workaround for hotkeys and menus: the keyword resp. the python classes define are only "local" and so replaced by a unique "global" one before sent to the client. 
When triggered, the python event again is called with the local keyword/id.
