### ISSUE TITLE
Failed to load plugin.

### ISSUE THREAD

**Issue by Metvernichter** [pathmann/pyTSon#34]
Hi,

after i installed the plugin i got this error in the Teamspeak Plugin List.

**Comment by pathmann** [comment]
Are you on windows? If so, you have to move python35.dll manually from %%APPDATA%%\\\\TS3Client\\\\plugins\\\\pyTSon\\\\ to %%PROGRAMFILES%%\\\\Teamspeak 3 Client\\\\ once.

**Comment by Bluscream** [comment]
Why would you encode paths on github? xD
```
%APPDATA%\TS3Client\plugins\pyTSon\
```
to
```
%PROGRAMFILES%\Teamspeak 3 Client\
```

**Comment by pathmann** [comment]
[https://github.com/pathmann/pyTSon/blob/master/tools/bundle.py#L42](Copy+paste) ftw

**Comment by Metvernichter** [comment]
Thank you. I was silly and did not use the Beta. Sorry
