### ISSUE TITLE
uic in pytson?

### ISSUE THREAD

**Issue by Metvernichter** [pathmann/pyTSon#35]
Hi,
i tried to make a GUI for my plugin, but i dont know how to do that.

Can someone please help me?

I want to use a .ui-file.

**Comment by pathmann** [comment]
Untested piece of code (not fully runnable, but you'll get the idea):

```python3
from ts3plugin import ts3plugin
from PythonQt.QtGui import QDialog
from PythonQt.QtCore import Qt
from pytsonui import setupUi

class mydialog(QDialog):
  def __init__(self, parent=None):
    super().__init__(parent)
    self.setAttribute(Qt.WA_DeleteOnClose)

   setupUi(self, "path-to-your-ui-file.ui")
   #now eg. if you set a QPushButton in your ui-file (with objectname "mybutton"), it will be accessible via self.mybutton; slots are connected by name to this class

  def on_mybutton_clicked(self):
    print("hey, thx for clicking mybutton")


class myplugin(ts3plugin):
  """
  ...
  """
  def __init__(self):
    self.dlg = None

  def showConfigWindow(self):
    if not self.dlg:
      self.conf = mydialog()

    self.conf.show()
    self.conf.raise_()
```



P.S.: Of course you must not use pytsonui.setupUi and can instead use QUILoader yourselve.

**Comment by Metvernichter** [comment]
Now i got a message that setupui need an argument "widget". In the documentation it says its optional.
Hope you can help me. Nothing works for me.

**Comment by pathmann** [comment]
Sorry, I forgot that I changed that for v1.0.5. So if you wanna use it, you have three options:
1. Wait for v1.0.5 and update then
2. Replace your pytsonui.py with the one from master, it should be downward compatible
3. Use setupUi with the (not optional) parameter widget

**Comment by Metvernichter** [comment]
With 1.0.5 it works like a charm!

Thank you.
