### ISSUE TITLE
threading?

### ISSUE THREAD

**Issue by Metvernichter** [pathmann/pyTSon#36]
Hey,

i cant find a way to run some code in a seperate thread.

```
import time, threading

    def __init__(self):
        t = threading.Thread(target=self.test())
        t.start()    

    def test(self):   
        while True:
            time.sleep(1)
            ts3.printMessageToCurrentTab("yeah")
```

**Comment by pathmann** [comment]
See #3

**Comment by Bluscream** [comment]
If you want to create sleeps/loops that don't make the client freeze just use http://doc.qt.io/qt-5/qtimer.html

**Comment by Metvernichter** [comment]
omg. you made my day/night!

**Comment by Bluscream** [comment]
haha lol :3

**Comment by Bluscream** [comment]
btw du kannst ja auch mal ne repo JSON aufsetzen

- https://github.com/pathmann/pyTSon_repository/blob/master/repository.json
- https://github.com/Bluscream/pyTSon_plugins/blob/master/ressources/bluscream.json
