### ISSUE TITLE
How to use InfoData in pyTSon?

### ISSUE THREAD

**Issue by Bluscream** [pathmann/pyTSon#4]
I would like to use the infoData section in pyTSon, can i get some documentation/help to accomplish it?

I need it to port https://github.com/Bluscream/Extended-Info-Plugin/blob/master/src/plugin.c#L183 to pyTSon.

P.S. Why isn't there a proper switch/case in python :/ https://www.pydanny.com/why-doesnt-python-have-switch-case.html

This is what i got so far :O 
```python
from ts3plugin import ts3plugin, PluginHost
import ts3, ts3defines, datetime


class info(ts3plugin):
    name = "info"
    apiVersion = 21
    requestAutoload = True
    version = "1.0"
    author = "Bluscream"
    description = "Shows you more informations.\n\nCheck out https://r4p3.net/forums/plugins.68/ for more plugins."
    offersConfigure = False
    commandKeyword = ""
    infoTitle = "Extended Info: "
    menuItems = []
    hotkeys = []


    def __init__(self):
        ts3.printMessageToCurrentTab('[{:%Y-%m-%d %H:%M:%S}] '.format(datetime.datetime.now())+"Extended Info Plugin for pyTSon by Bluscream loaded.")

    #def infoData(cls, schid, id, atype):
        #switch(atype)
```

**Comment by svenpaulsen** [comment]
The _infoData_ method you implement in your Python plugin must return a list of strings that will be pushed into the char* array of the _ts3plugin_infoData_ function.

About the switch/case thing... I think due to the special syntax of Python, a switch/case would not make any sense. Just use an if statement instead. It will basically look the same, gives you more flexibility for conditions and your code will be shorter.

https://docs.python.org/3/tutorial/controlflow.html#if-statements

**Comment by Bluscream** [comment]
@svenpaulsen So something like this would be the best solution?
```python
    def infoData(cls, schid, id, atype):
         if atype == 0:
             return ts3.printMessageToCurrentTab("Clicked on a Server.")
         elif atype == 1:
             return ts3.printMessageToCurrentTab("Clicked on a Client.")
         elif atype == 2:
             return ts3.printMessageToCurrentTab("Clicked on a Channel.")
         else:
             return ts3.printMessageToCurrentTab("ItemType \""+str(atype)+"\" unknown.")
```

**Comment by Bluscream** [comment]
![image](https://cloud.githubusercontent.com/assets/3318223/19411657/023af056-9306-11e6-8044-6db45b2c303e.png)

This doesn't look right to me xD

**Comment by pathmann** [comment]
Because you returned strings, which in this case are recognized as lists of characters. 

So pass list of strings as return value and you should be good (return ["Channel"]).

**Comment by Bluscream** [comment]
@pathmann Thanks that fixed it :3 My next question is where i can find the required parameters of a ts3. function?

```
15.10.2016 16:56:08	pyTSon	Error	Calling infoData failed with error "Error calling method
Traceback (most recent call last):
  File "C:/Users/blusc_000/AppData/Roaming/TS3Client/plugins/pyTSon/scripts\ts3plugin.py", line 167, in callMethod
    return meth(*args)
  File "C:/Users/blusc_000/AppData/Roaming/TS3Client/plugins/pyTSon/scripts\ts3plugin.py", line 200, in infoData
    ret += p.infoData(schid, id, atype)
  File "C:/Users/blusc_000/AppData/Roaming/TS3Client/plugins/pyTSon/scripts\info.py", line 24, in infoData
    return [ts3.getServerVariableAsString(39)]
TypeError: function takes exactly 2 arguments (1 given)
"	
```

**Comment by pathmann** [comment]
Either directly from the source (https://github.com/pathmann/pyTSon/blob/master/generated/pregen/ts3module.cpp) or from the (incomplete) documentation, which is generated from the source: https://pytson.4qt.de/ts3module.ts3-class.html

**Comment by Bluscream** [comment]
Ahh so langsam wird mir manches klar :D 
```python
    def infoData(cls, schid, id, atype):
         if atype == 0:
             schid = ts3.getCurrentServerConnectionHandlerID()
             error, ip = ts3.getServerVariableAsString(schid, ts3defines.VirtualServerPropertiesRare.VIRTUALSERVER_IP)
             return [ip]
         elif atype == 1:
             return ["Channel"]
         elif atype == 2:
             return []
         else:
             return ["ItemType \""+str(atype)+"\" unknown."]
```

**Comment by Bluscream** [comment]
@pathmann This event doesn't seem to trigger for me :(
```python
    def onMenuItemEvent(cls, schid, atype, menuItemID, selectedItemID):
        ts3.printMessageToCurrentTab(str(atype))
        ts3.printMessageToCurrentTab(str(menuItemID))
        ts3.printMessageToCurrentTab(str(selectedItemID))
        return ts3.printMessageToCurrentTab(str(atype))
```

**Comment by pathmann** [comment]
Make sure, the class attribute menuItems is set:
```
class yourplugin(ts3plugin):
  menuItems = [(ts3defines.PluginMenuType.PLUGIN_MENU_TYPE_CLIENT, 0, "My Menu Item", "icon.png")]

  def onMenuItemEvent(self, schid, atype, menuItemID, selectedItemID):
    if menuItemID == 0:
      print("menu item pressed")
```

**Comment by Bluscream** [comment]
@pathmann ```python
from ts3plugin import ts3plugin, PluginHost
import ts3, ts3defines, datetime


class info(ts3plugin):
    name = "Extended Info"
    apiVersion = 20
    requestAutoload = True
    version = "1.0"
    author = "Bluscream"
    description = "Shows you more informations.\nBest to use together with a Extended Info Theme.\n\nCheck out https://r4p3.net/forums/plugins.68/ for more plugins."
    offersConfigure = False
    commandKeyword = ""
    infoTitle = ""
    menuItems = [(ts3defines.PluginMenuType.PLUGIN_MENU_TYPE_GLOBAL, 0, "Extended Info -> Toggle Colors", "icon.png"),(ts3defines.PluginMenuType.PLUGIN_MENU_TYPE_GLOBAL, 0, "Extended Info -> Toggle Meta", "icon.png")]
    hotkeys = []
    colored = False


    def __init__(self):
        ts3.printMessageToCurrentTab('[{:%Y-%m-%d %H:%M:%S}] '.format(datetime.datetime.now())+"Extended Info Plugin for pyTSon by Bluscream loaded.")

    def onMenuItemEvent(self, schid, atype, menuItemID, selectedItemID):
        if menuItemID == 0:
        print("menu item pressed")

    def infoData(cls, schid, id, atype):
```

**Comment by pathmann** [comment]
The second part of the tuple is a local id, so they have to be unique.
`menuItems = [(ts3defines.PluginMenuType.PLUGIN_MENU_TYPE_GLOBAL, 0, "Extended Info -> Toggle Colors", "icon.png"),(ts3defines.PluginMenuType.PLUGIN_MENU_TYPE_GLOBAL, 1, "Extended Info -> Toggle Meta", "icon.png")]`

There is some indentation missing, I guess, you mean:
```
def onMenuItemEvent(self, schid, atype, menuItemID, selectedItemID):
        if menuItemID == 0:
                print("menu item pressed")
        elif menuItemID == 1:
                print("second menu item pressed")
```

**Comment by Bluscream** [comment]
```python
from ts3plugin import ts3plugin, PluginHost
import ts3, ts3defines, datetime


class info(ts3plugin):
    name = "Extended Info"
    apiVersion = 20
    requestAutoload = True
    version = "1.0"
    author = "Bluscream"
    description = "Shows you more informations.\nBest to use together with a Extended Info Theme.\n\nCheck out https://r4p3.net/forums/plugins.68/ for more plugins."
    offersConfigure = False
    commandKeyword = ""
    infoTitle = ""
    menuItems = [(ts3defines.PluginMenuType.PLUGIN_MENU_TYPE_GLOBAL, 0, "Extended Info -> Toggle Colors", "icon.png"),(ts3defines.PluginMenuType.PLUGIN_MENU_TYPE_GLOBAL, 1, "Extended Info -> Toggle Meta", "icon.png")]
    hotkeys = []
    colored = False


    def __init__(self):
        ts3.printMessageToCurrentTab('[{:%Y-%m-%d %H:%M:%S}] '.format(datetime.datetime.now())+"Extended Info Plugin for pyTSon by Bluscream loaded.")

    def onMenuItemEvent(self, schid, atype, menuItemID, selectedItemID):
        if menuItemID == 0:
            ts3.printMessageToCurrentTab("menu item pressed")
        elif menuItemID == 1:
            ts3.printMessageToCurrentTab("second menu item pressed")

    def infoData(cls, schid, id, atype):
``` clicking on one of the menu items now only prints "0" in the chat

**Comment by pathmann** [comment]
Your code works here. Did you restart the plugin (or for best results, your client)?

If this does not help, it's a bug. On which platform do you run your code?

**Comment by Bluscream** [comment]
Win x64

**Comment by pathmann** [comment]
Works on my win64 vm, so I guess this was already fixed (eventually with #1f7d560375500b83073db4c025df5eb6326c23e0).

So either you update your ts3 client to 3.1 or you compile pyTSon for api version 20.

**Comment by Bluscream** [comment]
@pathmann I meant Windows 8 x64 Teamspeak 3.1 x64 (Script API 20)

**Comment by pathmann** [comment]
Self compiled (if so, clone from current head?) or release from here (if so, which?)?

**Comment by Bluscream** [comment]
[Latest release](https://github.com/pathmann/pyTSon/releases/tag/v1.0.3)

**Comment by pathmann** [comment]
Can't reproduce. Can you post your full code?

Tested this:
```python
from ts3plugin import ts3plugin, PluginHost
import ts3, ts3defines, datetime


class info(ts3plugin):
    name = "Extended Info"
    apiVersion = 20
    requestAutoload = True
    version = "1.0"
    author = "Bluscream"
    description = "Shows you more informations.\nBest to use together with a Extended Info Theme.\n\nCheck out https://r4p3.net/forums/plugins.68/ for more plugins."
    offersConfigure = False
    commandKeyword = ""
    infoTitle = ""
    menuItems = [(ts3defines.PluginMenuType.PLUGIN_MENU_TYPE_GLOBAL, 0, "Extended Info -> Toggle Colors", "icon.png"),(ts3defines.PluginMenuType.PLUGIN_MENU_TYPE_GLOBAL, 1, "Extended Info -> Toggle Meta", "icon.png")]
    hotkeys = []
    colored = False


    def __init__(self):
        ts3.printMessageToCurrentTab('[{:%Y-%m-%d %H:%M:%S}] '.format(datetime.datetime.now())+"Extended Info Plugin for pyTSon by Bluscream loaded.")

    def onMenuItemEvent(self, schid, atype, menuItemID, selectedItemID):
        if menuItemID == 0:
            ts3.printMessageToCurrentTab("menu item pressed")
        elif menuItemID == 1:
            ts3.printMessageToCurrentTab("second menu item pressed")

```

**Comment by Bluscream** [comment]
https://gist.github.com/Bluscream/79f8ee59a92dbd3a60327d3a0f7504ed

**Comment by pathmann** [comment]
![pytson_menuitems](https://cloud.githubusercontent.com/assets/3155203/19413583/d457edf2-9331-11e6-9544-27c44be1fa00.png)

Still, can't reproduce this, sorry.

**Comment by Bluscream** [comment]
Hmm i don't know. I'll try to restart my client and my PC.

**Comment by pathmann** [comment]
> BTW. since i'm very unfamiliar with QT i would request a small plugin from you which can toggle the serverbanners.
Don't know, what you mean.

> Also does the API bring something like a settings panel that i can use?
There are two more or less complex examples on how to get a gui in pyTSon in pyTSon's code itself (https://github.com/pathmann/pyTSon/tree/master/ressources).

**Comment by Bluscream** [comment]
![image](https://cloud.githubusercontent.com/assets/3318223/19413909/b40d9eba-933c-11e6-8d44-a615733b884e.png)
I mean a plugin to set this banner_gfx to hidden by default. So it just doesn't show up and takes space

**Comment by pathmann** [comment]
In this case, my [tweakui example](https://github.com/pathmann/pyTSon_plugins/blob/master/scripts/tweakui.py) is a good starting point.

**Comment by Bluscream** [comment]
@pathmann Yeah i've seen it. It's a great resource for more advanced devs but for me Qt stuff reads "中央火车站" :D

**Comment by Bluscream** [comment]
![image](https://cloud.githubusercontent.com/assets/3318223/19414297/5cf8ac76-9348-11e6-9228-8deefe6db22b.png)

![image](https://cloud.githubusercontent.com/assets/3318223/19414298/6a7f1ef2-9348-11e6-983d-5b87dfb1d87f.png)
@pathmann

**Comment by pathmann** [comment]
![pytson_getclientid](https://cloud.githubusercontent.com/assets/3155203/19416408/b45161a6-938f-11e6-9bd4-f1dc8581ae83.png)

Formatchar "K" extracts an unsigned long long, not string: [here](https://github.com/pathmann/pyTSon/blob/master/generated/pregen/ts3module.cpp#L830)

Can't reproduce this either. But I experienced sometimes wrong line numbers in tracebacks (don't know if it's a bug, or I changed the running source file). So maybe the exception belongs to another line?
