### ISSUE TITLE
Disable/Enable menuItems

### ISSUE THREAD

**Issue by Bluscream** [pathmann/pyTSon#40]
https://github.com/Kleberstoff/TS-Plugins-API-21/blob/master/anti-move/src/plugin.c#L161

```
	ts3Functions.setPluginMenuEnabled(pluginID, Rubberband_Enabled, 1);
	ts3Functions.setPluginMenuEnabled(pluginID, Rubberband_Disabled, 0);
````

I wish this would exist in pyTSon

**Comment by Bluscream** [comment]
Fixed with https://github.com/pathmann/pyTSon/commit/110e9d8aa6319874f5ead2ccc659a564110d2680

**Comment by pathmann** [comment]
PluginHost.globalMenuID is currently undocumented (and there was a bug, fixed in master), but with the next release it should work.

```python
from ts3plugin import ts3plugin, PluginHost

import ts3defines, ts3lib


class menutest(ts3plugin):
    name = "menutest"
    requestAutoload = False
    version = "1.0.0"
    apiVersion = 21
    author = "Thomas \"PLuS\" Pathmann"
    description = "Showcase to enable/disable pluginmenus"
    offersConfigure = False
    commandKeyword = "menu"
    infoTitle = None
    menuItems = [(ts3defines.PluginMenuType.PLUGIN_MENU_TYPE_GLOBAL, 0, "Menutest", "icon.png")]
    hotkeys = []

    def __init__(self):
        self.dlg = None

    def stop(self):
        pass

    def onMenuItemEvent(self, schid, atype, menuItemID, selectedItemID):
        if menuItemID == 0:
            print("menu clicked")

    def enableMenu(self, on):
        globid = PluginHost.globalMenuID(self, 0)

        if globid:
            ts3lib.setPluginMenuEnabled(globid, on)

    def processCommand(self, schid, command):
        tokens = command.split(' ')

        if len(tokens) == 0:
            return False

        if tokens[0] == "enable":
            self.enableMenu(True)
            return True
        elif tokens[0] == "disable":
            self.enableMenu(False)
            return True

        return False
```

**Comment by Bluscream** [comment]
Does your code still apply to https://github.com/pathmann/pyTSon/commit/229c1379f9914742218a784fa4b0e387f223bad7 ?

**Comment by pathmann** [comment]
> Does your code still apply to 229c137 ?

Yes.

> Also .globalMenuID() seems to only apply to global menus, what about channel and client ones?

No, that's not the meaning of "global" in that function. Every plugin uses "local identifier" to reference only the menuItems, this specific plugin uses. The PythonHost translates them to "global identifiers" and sends them to the TS3 client. With this method, it is not necessary, that each plugin uses unique identifiers.

> I'd also suggest splitting https://github.com/pathmann/pyTSon_repository/blob/master/repository.json into a production and a development/test repo and adding the snippet above to the test repo.

The masterplan is, to update the documentation.
