### ISSUE TITLE
[Question] Max length for infoData ?

### ISSUE THREAD

**Issue by Bluscream** [pathmann/pyTSon#45]
![image](https://cloud.githubusercontent.com/assets/3318223/22605914/3bf9b536-ea52-11e6-8eb7-dbbb6835a1ab.png)

Seems like it got cutted off?

**Comment by pathmann** [comment]
There is no restriction in pyTSon, so this seems to be a TS3 Client/lib restriction. Can't change it here. Feel free to report it to TeamSpeak Systems.

**Comment by Bluscream** [comment]
I will thanks for making that clear :+1:

**Comment by thorwe** [comment]
Formats aren't my strong suit, but I think you're reserving / copying not enough bytes.
https://github.com/pathmann/pyTSon/blob/master/src/pythonhost.cpp#L401
Something like
const auto kStrUtf = str.toUtf8();
const auto kSize = kStrUtf.size() + 1;
*data = (char*)malloc(kSize);
strncpy(*data, kStrUtf.data(), kSize);

**Comment by thorwe** [comment]
Looking at it, it's probably more like
const auto kSize = kStrUtf.size();
data = (char)malloc(kSize + 1);
data[kSize+1]=0; // isn't initialized with zero using malloc, is it
strncpy(*data, kStrUtf.data(), kSize);  // don't copy kSize+1 as on comment before.

(Sorry, too busy to do the whole repo clone, check, pull request routine, point being QString length and size funcs return number of characters, Bluscream's screenshot shows some funky nickname including characters that won't fit into a char, i.e. UTF-8. Hence toUtf8'ing it first, the resulting QByteArray size function then returning size in bytes.)

**Comment by pathmann** [comment]
> (Sorry, too busy to do the whole repo clone, check, pull request routine, point being QString length and size funcs return number of characters, Bluscream's screenshot shows some funky nickname including characters that won't fit into a char, i.e. UTF-8. Hence toUtf8'ing it first, the resulting QByteArray size function then returning size in bytes.)

No need to, I'll look into it and check.

**Comment by pathmann** [comment]
Fixed with 15c7d2b.
