### ISSUE TITLE
infoData AttributeError when 'onClientSelfVariableUpdateEvent' called

### ISSUE THREAD

**Issue by Scrxtchy** [pathmann/pyTSon#46]
I've been using the 'onClientSelfVariableUpdateEvent' to monitor when I switch my `Active Microphone`, as in comparison to what the active tab is. I store it in a variable since I have no knowledge if this variable is on available from ts3lib.

My Code looks a little like
```py
def onClientSelfVariableUpdateEvent(self, serverConnectionHandlerID, flag, oldValue, newValue):
		if flag == ts3defines.ClientProperties.CLIENT_INPUT_HARDWARE:
			ts3lib.printMessageToCurrentTab("Switched Server Mic to %s" % serverConnectionHandlerID)
```

So I am unsure why I am getting this in my Client Log whenever `Activate Microphone` is clicked
```
  File "C:/Users/Scratch/AppData/Roaming/TS3Client/plugins/pyTSon/scripts\ts3plugin.py", line 303, in infoData
    ret += p.infoData(schid, aid, atype)
AttributeError: 'fooplugin' object has no attribute 'infoData'
```

**Comment by pathmann** [comment]
Fixed with 7d1ccd2 for the next release.

As a workaround, you can set infoTitle to None (as the [docs](https://pytson.4qt.de/plugin.ts3plugin-class.html#infoTitle) state), so the infoData method won't be called. Background: in previous version, the ts3plugin class implemented all callbacks and returned default values. To omit empty lines in infoData, plugins had to set infoTitle to None to show, that they don't use infoData at all.

**Comment by pathmann** [comment]
>I store it in a variable since I have no knowledge if this variable is on available from ts3lib.

Btw.: You can always query this flag with [ts3lib.getClientSelfVariableAsInt](https://pytson.4qt.de/ts3module.ts3-class.html#getClientSelfVariableAsInt):
```
val = ts3lib.getClientSelfVariableAsInt(schid, ts3defines.ClientProperties.CLIENT_INPUT_HARDWARE)
```

**Comment by Scrxtchy** [comment]
Querying the client_input_hardware will only return a 0 or 1 if I provide the correct schid, which I don't find as effective if I have to loop though to find the response, but thanks anyway

**Comment by Bluscream** [comment]
There is a event that gets fired when the currentConnectionhandler changes, but its name is quite irritating.
