### ISSUE TITLE
ts3lib.getAvatar returns other client's avatar sometimes

### ISSUE THREAD

**Issue by Scrxtchy** [pathmann/pyTSon#47]
Here's my function to return information about users
```py
users = ts3lib.getChannelClientList(serverConnectionHandlerID, getChannelID(serverConnectionHandlerID))[1]
	userDetailed = []
	for user in users:
		userDetailed.append([user, ts3lib.getClientDisplayName(serverConnectionHandlerID, user)[1], ts3lib.getAvatar(serverConnectionHandlerID, user)[1]])
	return userDetailed
```

And returns data that looks like this
```
[[10, "foo", "C:\\Users\\Scratch\\AppData\\Roaming\\TS3Client\\cache/cXpvUndERUt4cHpNeVh5NVVEQUNRaVQ5Zml3PQ==/clients/avatar_kknfagbmpjknepljpopjnfjmgphbafgpnlgbgjbo"], [12, "bar", "C:\\Users\\Scratch\\AppData\\Roaming\\TS3Client\\cache/cXpvUndERUt4cHpNeVh5NVVEQUNRaVQ5Zml3PQ==/clients/avatar_kknfagbmpjknepljpopjnfjmgphbafgpnlgbgjbo"], [36, "baz", "C:\\Users\\Scratch\\AppData\\Roaming\\TS3Client\\cache/cXpvUndERUt4cHpNeVh5NVVEQUNRaVQ5Zml3PQ==/clients/avatar_ffjanefihehaffajfkachcnmpkilkgnbdjohbjbn"], [37, "aye", "C:\\Users\\Scratch\\AppData\\Roaming\\TS3Client\\cache/cXpvUndERUt4cHpNeVh5NVVEQUNRaVQ5Zml3PQ==/clients/avatar_inigkkngpkghnjffhpfpaalhpnddahndceikacle"]]
```
While this doesn't always happen, but has in this case,
User `bar`, `12` has the same Avatar path as `foo`,`10`
I have error checking built into the front-end of the data (which is used to convert paths from back to forwardslash), but it doesn't catch an error when it gives a valid, yet incorrect path

**Comment by Scrxtchy** [comment]
I've also just encountered one with
`"C:\\Users\\Scratch\\AppData\\Roaming\\TS3Client\\"`

**Comment by pathmann** [comment]
> I have error checking built into the front-end of the data 

But you don't check any errors of the ts3lib functions.

**Comment by Scrxtchy** [comment]
They return 1281 ts3lib errors as expected, but it’s strange that even with this error, they are still returning responses

```
0 | C:\Users\Scratch\AppData\Roaming\TS3Client\cache/aUptQVAwNUFtYTBFUXY4UjdjTERqbkdtT0tnPQ==/clients/avatar_bidfijekbcbkflhlhmpohpgflecgmiiakikiccbo
1281 | C:\Users\Scratch\AppData\Roaming\TS3Client\cache/aUptQVAwNUFtYTBFUXY4UjdjTERqbkdtT0tnPQ==/clients/avatar_bidfijekbcbkflhlhmpohpgflecgmiiakikiccbo
1281 |
1281 |
0 | C:\Users\Scratch\AppData\Roaming\TS3Client\cache/aUptQVAwNUFtYTBFUXY4UjdjTERqbkdtT0tnPQ==/clients/avatar_hegigdadicikfcmcaahbalheenadjgkfnehblmpd
0 | C:\Users\Scratch\AppData\Roaming\TS3Client\cache/aUptQVAwNUFtYTBFUXY4UjdjTERqbkdtT0tnPQ==/clients/avatar_mmhdoohlflmilkjaighjpkbbiagmephcnadngiob
0 | C:\Users\Scratch\AppData\Roaming\TS3Client\cache/aUptQVAwNUFtYTBFUXY4UjdjTERqbkdtT0tnPQ==/clients/avatar_inigkkngpkghnjffhpfpaalhpnddahndceikacle
1281 |
1281 | C:\Users\Scratch\AppData\Roaming\TS3Client\cache/aUptQVAwNUFtYTBFUXY4UjdjTERqbkdtT0tnPQ==/clients/avatar_inigkkngpkghnjffhpfpaalhpnddahndceikacle
1281 |
```

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by pathmann** [comment]
Please, check for errorcodes, they are usefull!

The values returned because of some not initialized memory in the c-part.

**Comment by Scrxtchy** [comment]
>The values returned because of some not initialized memory in the c-part.

Thanks :)

**Comment by Scrxtchy** [comment]
Hmm, This one has returned no error, but no valid path,
I can fix this in a post check, but I consider this a valid error
![](https://jii.moe/SyItP6WFl.png)

**Comment by pathmann** [comment]
You get the filepath to the avatar in your clients cache. So if the client did not download the avatar (eg by clicking the client in your tree), there is no cache hit. 
please check that. 

If that's the case, I'll consider this as an upstream bug (getavatar should not return 0 in this case imho).

I'm not sure, if calling requestclientvariables triggers downloading the avatar (can't test it currently). 
But if getavatar returns tuple(0,""), you could download the avatar from channel with clid=0 yourselve.

**Comment by pathmann** [comment]
You get ERROR_database_empty_result, if the user does not have an avatar and ERROR_file_io_error if the client could not load the icon (the TS3 client itself shows the broken_image image from the current iconpack).

Could not reproduce a return of tuple(0, ""). 

But I did receive some unicode decode exceptions two times, could not reproduce them either.
