### ISSUE TITLE
Dependencies?

### ISSUE THREAD

**Issue by Bluscream** [pathmann/pyTSon#5]
What dependencies are needed to install/run the plugin? Could you link their downloads here?

Equal to https://mfreiholz.de/ts3video/docs/#faq

**Comment by pathmann** [comment]
Dependencies are listed in [the Readme](https://github.com/pathmann/pyTSon#dependencies).

**Comment by Bluscream** [comment]
I guess users don't need pythonQt to run it, but they need visual c/c++ runtimes. Thats what i mean.

**Comment by pathmann** [comment]
All (run) dependencies are either delivered by the plugin or by the TS3 client (in the case msvc runtime dependencies).

Windows releases on this github site are compiled with the same tools (MSVC version) like the client.
