### ISSUE TITLE
[Question] QWebView

### ISSUE THREAD

**Issue by Bluscream** [pathmann/pyTSon#51]
I would like to use a QWebView in one of my plugins to display a OAuth webpage.

```python
from PythonQt.QtGui import *
from PythonQt.QtCore import *
from PythonQt.QtNetwork import *
from PythonQt.Qt import *
from PythonQt.private import *
from PythonQt.QtSql import *
from PythonQt.QtUiTools import *
from PythonQt.Debug import *
d = QDialog()
view = QWebView(d)
```
does result in `NameError: name 'QWebView' is not defined`

I have seen http://pyqt.sourceforge.net/Docs/PyQt4/qwebview.html which states that QWebView is part of the [QtWebKit](http://pyqt.sourceforge.net/Docs/PyQt4/qtwebkit.html).
``` import PythonQt.QtWebKit ``` does not seem to help either.

My question is, is it even a part of pyTSon and if not how can i add it?

**Comment by pathmann** [comment]
Indeed, the Qt WebKit (and webkitwidgets) Qt modules are not generated, see https://github.com/pathmann/PythonQt/blob/patched-6/generator/build_all.txt.

To avoid the need to deploy the Qt libraries, the contained PythonQt wraps only a subset of the Qt modules and classes, provided by the TeamSpeak 3 client itself and Qt Webkit is not (currently only QtCore, QtGui/QtWidgets, QtSql, QtNetwork and QtUiTools).
Deployed, but currently not wrapped: QtWebengine + Widgets, QtDBus (on Linux), QtPositioning, Qml + QtQuick, XcbQpa

I might wrap some of them in the future, but there are currently no plans for that.

P.S.: I suggest not using the PyQt (essentially not PyQt4) docs to lookup some PythonQt features. PyQt uses some other approaches to wrap Qt classes with sip.

So https://doc.qt.io/archives/qt-5.5/qwebview.html and http://pythonqt.sourceforge.net/ are much better resources.

**Comment by Bluscream** [comment]
Do you suggest opening the URL in a external browser or kinda "manipulate" the webview teamspeak uses to show the addon browser :)

**Comment by pathmann** [comment]
I definitely don't suggest the latter (if it's even possible).
