### ISSUE TITLE
clientChatClosed() not working?

### ISSUE THREAD

**Issue by Bluscream** [pathmann/pyTSon#52]
```python
def onUpdateClientEvent(self, schid, clientID, invokerID, invokerName, invokerUniqueIdentiﬁer):
      (error, ownid) = ts3lib.getClientID(schid)
      (error, _uid) = ts3lib.getClientVariableAsString(schid, ownid, ts3defines.ClientProperties.CLIENT_UNIQUE_IDENTIFIER)
      ts3lib.clientChatClosed(schid, _uid, clientID)
```

Does not seem to work for some oddly reason. I neither get the event nor the text in the chat tab.

**Comment by pathmann** [comment]
![screenshot from 2017-03-17 13-12-18](https://cloud.githubusercontent.com/assets/3155203/24042683/6502a398-0b13-11e7-9897-f6df597ce1f3.png)

Can't reproduce. Obviously there must be a "pipeline" open (chat tab opened and something was send).

**Comment by Bluscream** [comment]
Hmm, i'm trying to run it from https://github.com/Bluscream/pyTSon_plugins/blob/master/scripts/welcomeBot/__init__.py#L151

**Comment by pathmann** [comment]
So we agree, that it's no pyTSon or upstream bug?

I'd suggest adding returnCodes and sending the event in onServerErrorEvent.
