### ISSUE TITLE
Follow redirects for repos/plugins

### ISSUE THREAD

**Issue by Bluscream** [pathmann/pyTSon#57]
otherwise this happens:
![image](https://cloud.githubusercontent.com/assets/3318223/24655086/f3b345f2-193c-11e7-8e42-d5b660581eba.png)

Also following redirects would be nice for the repository urls themselves

**Comment by pathmann** [comment]
No description given.

**Comment by Bluscream** [comment]
Isn't the image descriptive enough? Or do you only accept PRs from now on?

**Comment by Scrxtchy** [comment]
This looks like bad news
