### ISSUE TITLE
[Request] Toggle certain events for all scripts

### ISSUE THREAD

**Issue by Bluscream** [pathmann/pyTSon#59]
In my opinion it could be useful to have a way to toggle events on and off globally so for example if none of the plugins use the onIncomingClientQueryEvent i could uncheck it's checkbox and it would not fire anymore from there on until i re-enable it.

**Comment by pathmann** [comment]
Why do you need that?

From the pyTSon perspective: It brings no real performance boost to omit certain events if such feature would be implemented in the python part of pyTSon (the function in PluginHost would be called no matter what, only the plugins won't). Implementing this into the pyTSon "core" (the C++ part) would break pyTSon's general design, which is "keep the core simple, implement as much as possible in python".

From the plugin perspective: If you don't need an event, don't add it to your class, so it won't be called.
If such a blacklist would exist, this could break some plugins. If for example unexperienced users blacklist some callbacks, which are essential for a plugin.
OK, such blacklist could be read by a plugin, but I like it the simple way. To check if callback A is blacklisted or not to react accordingly would make it more complex.
If you ask me, one argument for using pyTSon in favor of the original ts3 plugin sdk or the lua plugin is its simplicity. You simply do not need to care about api versions and such. 

From the user perspective: I can imagine some potential security issues (for example with onClientServerQueryLoginPasswordEvent). But imho if a user does not like some functions of a plugin, he should simply disable it or remove the features he doesn't like from the source.
It's the users choice and he should only use scripts from trustworthy sources or if he is able to, check the code of the plugins.

**Comment by Bluscream** [comment]
I get your point.
