### ISSUE TITLE
More (pre)-releases?

### ISSUE THREAD

**Issue by Bluscream** [pathmann/pyTSon#62]
I know that there are not enough changes to share the compiled plugin every day but as i look through my Activity Feed i see constant changes on the development and even on the master branch, so i would wish that you you publish release candidates from time to time. I personally go through the effort to download the source and extract/replace it's non C++ files but not everyone wants to do this. Since i want my plugins to be up to date whenever you release something new i already adopted various changes from the development branch, which makes them broken on your latest release from **Jan 27**. So i tried to keep atleast up a bit and created [this release](https://github.com/Bluscream/pyTSon/releases/tag/v1.1.0p1) for people that want to use my pytson scripts. But that doesn't seem like the ideal solution and also does not reflect any changes to the C part of the plugin which makes it easy to break. A official way to obtain a pre-release version would be nice and would not have to run through all your compilers unless someone requests a beta version specifically for OSX etc. Thanks for reading and i look forward to 1.1.1 (The commits look promising, especially the filetransfer UI stuff but sadly i was unable to test anything of that since january until today) :)

**Comment by pathmann** [comment]
This might sound a little egoistic, but I develop pyTSon primary for myself.
It's been a long way from a little plugin displaying some information of my current ts3 connection on the lcd of my g15 keyboard to the state pyTSon is now.
When I started to share my code here and release it to the public, I also always wanted to make it completely platform independent. So you'll understand that if (or when) **I** publish a release, there will be always a release for all available desktop platforms TS3 can run on. And that means I have to run three different virtual machines to create builds for the (current) 5 available platforms.

Now here comes the good news: when I commit some code here to the master branch, pyTSon should compile fine (although sometimes I forget to add new files to the bundle or docs scripts). So you should always be good to compile it for yourself.

Once the build system is setup (only a little tough on unix, where you need to compile python), it shouldn't be that hard. Once Qt (5.6.1[-x]) and python are installed (or compiled), you should only need to adapt some pathes in the project files.

> I personally go through the effort to download the source and extract/replace it's non C++ files but not everyone wants to do this.

Just for reference: I know this **can** work, but this is not supported. If pyTSon core (the C++ part) and python part don't fit together, it can break things. Currently I see no reason why it shouldn't work, but there are some things planned.
As the python source files have no reference to a specific version, this can lead to chaos imho.

**Comment by Bluscream** [comment]
I have asked several other people if they were able to compile atleast the x64 DLL but without any success. The effort to even build it just seems in no relation to the benefit of having the latest dev build for myself. (I've tried it for atleast 36 hours now if you count everything together)

**Comment by pathmann** [comment]
So you see that the complexity to maintain 5 builds is even higher. 

Make sure that you use "the ts3 client build environment". So qt 5.6.1(-x) and on windows use msvc 2015.
Where are you stuck?
