### ISSUE TITLE
File structure mismatch

### ISSUE THREAD

**Issue by Bluscream** [pathmann/pyTSon#63]
There seems to be some mismatch in the way `pyTSon-configdialog.ui` in atleast pyTSon_win64.ts3_plugin

config.py tries to load it from
```
"ressources", "pyTSon-configdialog.ui"
```
but its actually located at
```
"ressources", "ui", "pyTSon-configdialog.ui"
```

So you might either want to move it to the parent dir or edit the .py file :)
P.S. This happened on a fresh install only keeping the scripts dir

**Comment by pathmann** [comment]
There was a bug in the bundle script (Fixed with 6e0119f).

Either move the file pyTSon-configdialog.ui from ressources/ui to ressources or redownload the release (I uploaded a new one).
