### ISSUE TITLE
Also return default icons in ServerCache.icon()

### ISSUE THREAD

**Issue by Bluscream** [pathmann/pyTSon#65]
```py
cache = ts3client.ServerCache(schid)
ServerCache.icon(cache,100)
ServerCache.icon(cache,200)
ServerCache.icon(cache,300)
ServerCache.icon(cache,500)
ServerCache.icon(cache,600)
```
only return a empt Pixmaps. Using IconPack is of course possible but falling back to it by default when using ServerCache would be more convinient IMO

P.S. If this doesn't get implemented i'll leave https://github.com/Bluscream/pyTSon_plugins/blob/master/channelGroupChanger/__init__.py#L83-L86 as a reference for using group icons.

**Comment by pathmann** [comment]
Won't change.

The cache and the iconpack are two different things and adding iconpack functionality to the servercache would bloat it up imho.

Check for QPixmap::isNull whether the QPixmap is empty.
