### ISSUE TITLE
[1.2.0 | Windows | 32bit, 64bit] Window position of 'Online repository'

### ISSUE THREAD

**Issue by BradyThe** [pathmann/pyTSon#68]
The Online repository (+ pyTSon Plugin Installer) windows seems to orientate itself to screen position 0,0, while ignoring the title bar.

It's not a big deal, pretty low on the priority list, can easily be worked around, (is potentially once again my fault,) but I wanted to report it anyway just to let you know.

Cheers

![vmplayer_2017-05-18_12-44-02](https://cloud.githubusercontent.com/assets/8181555/26199445/4d663b72-3bca-11e7-9c90-5e65c5d5dae4.png)

**Comment by Bluscream** [comment]
I use [AltDrag](https://stefansundin.github.io/altdrag/) to move the window around :)

**Comment by BradyThe** [comment]
[Windows] + [Arrow key]s work too. ;-) Thanks for the tip, though, that program could come in handy.

**Comment by pathmann** [comment]
UIs created by setupUi will be centered on their parent within the next release (d94e7cc).
