### ISSUE TITLE
64bit upgrade issues

### ISSUE THREAD

**Issue by Scrxtchy** [pathmann/pyTSon#70]
First issue I faced was that ts3 would crash on startup
Log declared that the was no module `ts3defines`
instead I found `ts3defines.py` folder within the `scripts` directory, renaming it solved this issue, even though the plugin generated the folder again

then the next issue arose
```
017-09-13 05:16:03.002142|ERROR   |pyTSon        |   |Initializing PythonHost failed with "Error calling PluginHost.init
                                                       Traceback (most recent call last):
                                                         File "C:/Users/Scratch/AppData/Roaming/TS3Client/plugins/pyTSon/scripts\pluginhost.py", line 94, in init
                                                           cls.reload()
                                                         File "C:/Users/Scratch/AppData/Roaming/TS3Client/plugins/pyTSon/scripts\pluginhost.py", line 296, in reload
                                                           for key, p in cls.active.items():
                                                       AttributeError: type object 'PluginHost' has no attribute 'active'
                                                       "
```

Teamspeak doesn't crash until you open the client log within the interface
In addition, it detects that the plugin doesn't start correct so it isn't loaded at all

**Comment by pathmann** [comment]
Thx for the report, I can reproduce some odd behaviours due to the latest changes in the bundler script.

But I guess you mean ts3plugin.py (instead of ts3defines.py).
ts3defines should not be placed in the scripts directory at all. And if you struggle with ts3plugin.py being a folder (like here), it would explain your second error, which is just a follow up.

Either way, I'll have a look into it.

**Comment by Scrxtchy** [comment]
Thanks for the commit, must have just been a memory thing regarding the module

**Comment by pathmann** [comment]
I hope, the binaries attached to the release do work now.
