### ISSUE TITLE
onPluginCommandEvent not working?

### ISSUE THREAD

**Issue by Bluscream** [pathmann/pyTSon#76]
I use
```py
    def onPluginCommandEvent(self, schid, clid, pluginCommand):
        ts3lib.printMessageToCurrentTab("onPluginCommandEvent")
        ts3lib.printMessage(schid, "{} PluginMessage from {}: {}".format(self.timestamp(), self.clientURL(clid), pluginCommand), ts3defines.PluginMessageTarget.PLUGIN_MESSAGE_TARGET_SERVER)
```
but 
```c#
[ IN] notifyplugincmd name=sb data=ping:189
```
results in nothing. Not even the `onPluginCommandEvent` is printed :/

**Comment by pathmann** [comment]
Sounds like you trying to send a plugincommand with the clientquery plugin?

If so, this will never work. PluginCommands are only delivered to the same plugin on the receiving side (pyTSon user a can send commands to pyTSon user b and clientquery user c can send commands to clientquery user d).

**Comment by Bluscream** [comment]
But pytson plugincmds should be printed in either case; encrypted or the ones before the keystuff was added

---
Sent from my Lenovo TAB 2 A10-70L running Android 6.0 via OctoDroid v4.2.1

**Comment by Bluscream** [comment]
#77

---
Sent from my Lenovo TAB 2 A10-70L running Android 6.0 via OctoDroid v4.2.1

**Comment by pathmann** [comment]
That does not answer my question. Or show some more code (the sending part is missing at all).

I admit, that I didn't test this feature not that intensively as I should, but the tests I made worked very well. And the time spent with overhead was not noticeable.

**Comment by Bluscream** [comment]
Give me some time (im currently laying in my bed talking talking to my girlfriend) then i will sort what i've written and give you some concrete information.

**Comment by Bluscream** [comment]
Ah okay thanks for the info. Maybe provide a `onRawPluginCommand` for these cases, thanks <3

**Comment by pathmann** [comment]
See my comment in #75

**Comment by Bluscream** [comment]
Update: Seems like it's a platform dependent problem.

Also add proper return values to https://github.com/pathmann/pyTSon/blob/master/ressources/python/_plugincmd.py#L716
