### ISSUE TITLE
How to work with pluginMenus ?

### ISSUE THREAD

**Issue by Bluscream** [pathmann/pyTSon#81]
In [setPluginMenuEnabled](https://pytson.4qt.de/ts3lib-module.html#setPluginMenuEnabled) you say `Retrieve it with PluginHost.globalMenuID` and the [docstring of that function](https://pytson.4qt.de/pluginhost.PluginHost-class.html) says `globalMenuID(cls, plugin, localid)`

Now my question, what is `plugin`? is it a plugin object retrieved via some obscure `PluginHost.getPlugin()`-like function or just the plugin name or some plugin uuid or just a reference to the plugin class (therefor `self`)?

Also what kind of `localid` does the function need? Some mix between `PluginMenuType` and the actual id? The id is not unique; take the below code as example:
```py
    menuItems = [
        (ts3defines.PluginMenuType.PLUGIN_MENU_TYPE_GLOBAL, 0, "== {0} ==".format(name), ""),
        (ts3defines.PluginMenuType.PLUGIN_MENU_TYPE_GLOBAL, 1, "Some button", ""),
        (ts3defines.PluginMenuType.PLUGIN_MENU_TYPE_GLOBAL, 2, "Some other button", ""),
        (ts3defines.PluginMenuType.PLUGIN_MENU_TYPE_GLOBAL, 3, "== {0} ==".format(name), ""),
        (ts3defines.PluginMenuType.PLUGIN_MENU_TYPE_CHANNEL, 0, "== {0} ==".format(name), ""),
        (ts3defines.PluginMenuType.PLUGIN_MENU_TYPE_CHANNEL, 1, "bla", ""),
        (ts3defines.PluginMenuType.PLUGIN_MENU_TYPE_CHANNEL, 2, "bli", ""),
        (ts3defines.PluginMenuType.PLUGIN_MENU_TYPE_CHANNEL, 3, "blu", ""),
        (ts3defines.PluginMenuType.PLUGIN_MENU_TYPE_CHANNEL, 4, "== {0} ==".format(name), "")
    ]
```

**Comment by pathmann** [comment]
plugin is your plugin's name.

localid is the id you pass in menuItems (second item in tuple).


```python
class myplugin(ts3plugin):
  #...
  name = "pluginname"
  menuItems = [(ts3defines.PluginMenuType.PLUGIN_MENU_TYPE_GLOBAL, 42, "I'm a menuitem", "")]

  def somefunc(self):
    globid = PluginHost.globalMenuID(self.name, 42)
    ts3lib.setPluginMenuEnabled(globid, True)
```

**Comment by Bluscream** [comment]
hmm, strange ```py
class plugin(ts3plugin):
    name = "pluginname"
    menuItems = [
        (PluginMenuType.PLUGIN_MENU_TYPE_GLOBAL, 0, "== {0} ==".format(name), ""),
        (PluginMenuType.PLUGIN_MENU_TYPE_GLOBAL, 1, "asd", ""),
        (PluginMenuType.PLUGIN_MENU_TYPE_GLOBAL, 2, "asd", ""),
        (PluginMenuType.PLUGIN_MENU_TYPE_GLOBAL, 0, "== {0} ==".format(name), ""),
        (PluginMenuType.PLUGIN_MENU_TYPE_CHANNEL, 0, "== {0} ==".format(name), ""),
        (PluginMenuType.PLUGIN_MENU_TYPE_CHANNEL, 1, "asd", ""),
        (PluginMenuType.PLUGIN_MENU_TYPE_CHANNEL, 2, "asd", ""),
        (PluginMenuType.PLUGIN_MENU_TYPE_CHANNEL, 3, "asd", ""),
        (PluginMenuType.PLUGIN_MENU_TYPE_CHANNEL, 4, "asd", ""),
        (PluginMenuType.PLUGIN_MENU_TYPE_CHANNEL, 0, "== {0} ==".format(name), "")
    ]
    def menuCreated(self):
        ts3lib.setPluginMenuEnabled(PluginHost.globalMenuID(self.name, 0), False)
```
doesn't seem to disable anything :o

**Comment by pathmann** [comment]
My bad, the parameter plugin is only the plugin's name, if the plugin is not active.
So in mostly all cases, pass your plugin's object to that function.

```python
class myplugin(ts3plugin):
  #...
  name = "pluginname"
  menuItems = [(ts3defines.PluginMenuType.PLUGIN_MENU_TYPE_GLOBAL, 42, "I'm a menuitem", "")]
  #...

  def somefunc(self):
    globid = PluginHost.globalMenuID(self, 42)
    ts3lib.setPluginMenuEnabled(globid, True)
```

**Comment by Bluscream** [comment]
Works, but only with the global menuitems :/

Do i need to redo it onServerConnectionChanged?

**Comment by pathmann** [comment]
Quick test with
```python
ts3lib.setPluginMenuEnabled(PluginHost.globalMenuID(PluginHost.active["eventlog"], 0), False)
```
worked here.

**Comment by Bluscream** [comment]
isn't "eventlog" a global item?

I used:
```py
ts3lib.setPluginMenuEnabled(PluginHost.globalMenuID(self, 0), False)
```

**Comment by pathmann** [comment]
Eventlog is a ts3plugin.

**Comment by Bluscream** [comment]
Okay so i got it to work but i had to make the localid's unique :/

```py
class plugin(ts3plugin):
    name = "pluginname"
    menuItems = [
        (PluginMenuType.PLUGIN_MENU_TYPE_GLOBAL, 0, "== {0} ==".format(name), ""),
        (PluginMenuType.PLUGIN_MENU_TYPE_GLOBAL, 1, "asd", ""),
        (PluginMenuType.PLUGIN_MENU_TYPE_GLOBAL, 2, "asd", ""),
        (PluginMenuType.PLUGIN_MENU_TYPE_GLOBAL, 10, "== {0} ==".format(name), ""),
        (PluginMenuType.PLUGIN_MENU_TYPE_CHANNEL,11, "== {0} ==".format(name), ""),
        (PluginMenuType.PLUGIN_MENU_TYPE_CHANNEL, 1, "asd", ""),
        (PluginMenuType.PLUGIN_MENU_TYPE_CHANNEL, 2, "asd", ""),
        (PluginMenuType.PLUGIN_MENU_TYPE_CHANNEL, 3, "asd", ""),
        (PluginMenuType.PLUGIN_MENU_TYPE_CHANNEL, 4, "asd", ""),
        (PluginMenuType.PLUGIN_MENU_TYPE_CHANNEL, 12, "== {0} ==".format(name), "")
    ]
    def menuCreated(self):
        for id in [0,10,11,12]:
            ts3lib.setPluginMenuEnabled(PluginHost.globalMenuID(self, id), False)
```

**Comment by pathmann** [comment]
The docs (and a previous comment here) already stated that localids must be unique.

I don't see any reason to change this.

**Comment by Bluscream** [comment]
Good reasons would be flexibility, convinience, and not confusing/annyoing plugin devs like TSSystems GmbH does ;-)

**Comment by pathmann** [comment]
Confusing? Really? There is a documentation. Read it.
