### ISSUE TITLE
Problem with pyTSon [PHOTO]

### ISSUE THREAD

**Issue by EtexKG** [pathmann/pyTSon#84]
https://image.prntscr.com/image/AkPFsi2-R4O21VSeOyUnQQ.png

**Comment by pathmann** [comment]
Seems like your scripts source is malformed (contains a nullbyte).

The path to the script is in the first line of your screenshot (it's stripped, so I can't tell from here).

**Comment by Bluscream** [comment]
Do you still have that problem @EtexKG ? If not, please close your issue to mark it as solved :)

**Comment by pathmann** [comment]
Feel free to reopen, if needed ...
