### ISSUE TITLE
plugins not showing if placed in scripts folder

### ISSUE THREAD

**Issue by Haizanjs** [pathmann/pyTSon#86]
title says it all

**Comment by pathmann** [comment]
Please report back, if that solves your problem.

But please keep this issue open (as a reminder to update the README).

**Comment by Haizanjs** [comment]
C:\Users\MYUSER\AppData\Roaming\TS3Client\plugins\pyTSon\scripts\spampoke

doesnt work

**Comment by pathmann** [comment]
A little bit more info would be great...

Do you use the myteamspeam, the release version from here or the latest build from repo.4qt.de?

Does the client log contain any additional info? Please enable debug logging first.

**Comment by pathmann** [comment]
Feel free to reopen, if needed ...
