### ISSUE TITLE
Beta kann nicht geladen werden

### ISSUE THREAD

**Issue by SossenSystems** [pathmann/pyTSon#89]
Die derzeitige Beta kann auf Ubuntu Desktop (64 bit) nicht geladen werden.
Siehe https://www2.pic-upload.de/img/35233842/Bildschirmfotovom2018-04-2714-42-25.png

**Comment by pathmann** [comment]
Is this a duplicate of #87 ?

**Comment by SossenSystems** [comment]
Yes
