### ISSUE TITLE
Minor Bugs/Documentation typos

### ISSUE THREAD

**Issue by Bluscream** [pathmann/pyTSon#91]
- [ ] https://pytson.4qt.de/ts3lib-pysrc.html#getPluginPath lists parameters that are not accepted
- [ ] https://pytson.4qt.de/pytson-module.html#locales says it returns a string ([Screenshot](https://user-images.githubusercontent.com/3318223/40202369-45838c46-5a11-11e8-83c7-74786ff52f96.png))

**Comment by Bluscream** [comment]
How would one read the locales from the `Generator[str]` object? Is it iterable?

**Comment by pathmann** [comment]
https://wiki.python.org/moin/Generators

**Comment by Bluscream** [comment]
From the stuff that i think i've understood in that article it looks like i can iterate over it but it's just not creating a list for all locales if not needed, right?

**Comment by pathmann** [comment]
In short, yes.
