### ISSUE TITLE
Path seperators not consistent

### ISSUE THREAD

**Issue by Bluscream** [pathmann/pyTSon#92]
Can you give out any info on why they're diffrent at all?

```
(pyTSon v1.2.2~112ea43 on Windows-64bit | Console started at: 2018-05-16 16:24:07) Client curAPI: 21 | LibVer: (0, '3.1.9 [Build: 1525442084]') | LibVerNum: (0, 1525442084) Python win32 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55) [MSC v.1900 64 bit (AMD64)] API: 1013 sys.executable: C:/Users/blusc/AppData/Roaming/TS3Client/plugins/pyTSon/python.exe ts3lib.getAppPath(): C:/Program Files/TeamSpeak 3 Client/ ts3lib.getConfigPath(): C:\Users\blusc\AppData\Roaming\TS3Client\ ts3lib.getResourcesPath(): C:/Program Files/TeamSpeak 3 Client/ ts3lib.getPluginPath(): C:/Users/blusc/AppData/Roaming/TS3Client/plugins/ pytson.getConfigPath(): C:\Users\blusc\AppData\Roaming\TS3Client\pyTSon pytson.getPluginPath(): C:/Users/blusc/AppData/Roaming/TS3Client/plugins/pyTSon sys.path[0]"C:/Users/blusc/AppData/Roaming/TS3Client/plugins/pyTSon/scripts" sys.path[1]"C:/Users/blusc/AppData/Roaming/TS3Client/plugins/pyTSon/include" sys.path[2]"C:/Users/blusc/AppData/Roaming/TS3Client/plugins/pyTSon/lib" sys.path[3]"C:/Users/blusc/AppData/Roaming/TS3Client/plugins/pyTSon/lib/lib-dynload" sys.path[4]"C:/Users/blusc/AppData/Roaming/TS3Client/plugins/pyTSon/lib/site-packages"  sys.flags(debug=0, inspect=0, interactive=0, optimize=0, dont_write_bytecode=0, no_user_site=1, no_site=0, ignore_environment=1, verbose=0, bytes_warning=0, quiet=0, hash_randomization=0, isolated=0)
````

![grafik](https://user-images.githubusercontent.com/3318223/40123634-31dbc65a-5916-11e8-91e7-2dabf791fee1.png)

**Comment by pathmann** [comment]
Some pathes are set by pyTSon's core (the C part) with the help of QDir (sys.executable/ProgramName, sys.path). Qt uses "/" as universal separator (see http://doc.qt.io/qt-5/qdir.html).

Some pathes are exact copies of the result, the TS3 plugin sdk returns (ts3lib.getAppPath, ...).

Some pathes are the results of the coresponding TS3 plugin sdk function appended with a pyTSon directory (pytson.getConfigPath, ...).

But as long as each path uses consistent dir separators (which they obviously do), it should be fine (at least os.path is fine with it).

**Comment by Bluscream** [comment]
> But as long as each path uses consistent dir separators (which they obviously do), it should be fine (at least os.path is fine with it).

![grafik](https://user-images.githubusercontent.com/3318223/40138475-47adf842-593c-11e8-88a9-42040c8a469f.png)

**Comment by pathmann** [comment]
So? Show a case, where this is problematic.

Does '''python
with open(pytson.getPluginPath("test.txt"), "w") as f:
  f.write("blub")
'''
work as expected?
