### ISSUE TITLE
onServerErrorEvent return value being ignored

### ISSUE THREAD

**Issue by Bluscream** [pathmann/pyTSon#94]
According to the docs
> True, if the plugin handled the command, so the client will ignore it.

![](https://i.imgur.com/Ppiinaw.gif)

**Comment by pathmann** [comment]
https://www.chiark.greenend.org.uk/~sgtatham/bugs.html

**Comment by Bluscream** [comment]
So a "not to your satisfaction" reported bug does not exist? Thats great

**Comment by Bluscream** [comment]
I gave you a video demonstration of it. Thats almost as if i would show you a typo and you would ask me to rewrite the text that contains the typo

**Comment by pathmann** [comment]
No, but I want ANY description.

A video showing some code (which is not completely shown) nobody understands and some console output is not helpfull.

If your car is broken, the mechanic won't be able to help if you show him a video of you using the starter switch and nothing happens.
