### ISSUE TITLE
Why is this script not working?

### ISSUE THREAD

**Issue by GitSimonHub** [pathmann/pyTSon#95]
from ts3plugin import ts3plugin

import ts3lib, ts3defines
from os import path
from ts3plugin import ts3plugin

class userManager(ts3plugin):
    name = "userManager"
    requestAutoload = False
    version = "1.0"
    apiVersion = 21
    author = "Simon"
    description = "This is a testplugin"
    offersConfigure = True
    commandKeyword = "manager"
    infoTitle = ""
    menuItems = []
    hotkeys = []
	ini = path.join(ts3lib.getPluginPath(), "pyTSon", "scripts", "userManager", "cfg", "settings.ini")

    def __init__(self):
        ts3lib.printMessageToCurrentTab("The userManager script is now running! :)")
		if path.isfile(self.ini):
            self.config.read(self.ini)
            if not self.config.has_section('general'):
                self.config.add_section('general')
                self.config.set('general', 'admin', "10")
                self.config.set('general', 'operator', "11")
                self.config.set('general', 'ban', "12")
                self.config.set('general', 'message', "Du bist geblockt.")
				self.config.set('general', 'autoTalk', "True")
                self.config.set('general', 'autoOperator', "True")
                self.config.set('general', 'autoBan', "True")
			else:
				self.config['general'] = {"admin": "10", "operator": "11", "ban": "12", "message": "Du bist geblockt.", "autoTalk": "True", "autoOperator": "True", "autoBan": "True" }

    def stop(self):
        ts3lib.printMessageToCurrentTab("The userManager script has stopped! :(")

    def onNewChannelEvent(self, schid, channelID, channelParentID):
        err, name = ts3lib.getChannelVariableAsString(schid, channelID, ts3defines.ChannelProperties.CHANNEL_NAME)
        if err == ts3defines.ERROR_ok:
            ts3lib.printMessageToCurrentTab("new channel %s" % name)
        else:
            ts3lib.printMessageToCurrentTab("got error %s" % err)

i have in the "userManager" folder a "cfg" folder with the settings.ini
but pyTSon is not showing this script

**Comment by GitSimonHub** [comment]
also keine " sondern '?

**Comment by Bluscream** [comment]
backticks (`)

**Comment by GitSimonHub** [comment]
Ich habe mal ausprobiert, wenn ich die dinge die ich hier jetzt mit einem ! markiere entferne, wird das script angezeigt.

from ts3plugin import ts3plugin

import ts3lib, ts3defines
from os import path
from ts3plugin import ts3plugin

class userManager(ts3plugin):
    name = "userManager"
    requestAutoload = False
    version = "1.0"
    apiVersion = 21
    author = "Simon"
    description = "This is a testplugin"
    offersConfigure = True
    commandKeyword = "manager"
    infoTitle = ""
    menuItems = []
    hotkeys = []
!	ini = path.join(ts3lib.getPluginPath(), "pyTSon", "scripts", "userManager", "cfg", "settings.ini")

    def __init__(self):
        ts3lib.printMessageToCurrentTab("The userManager script is now running! :)")
!		if path.isfile(self.ini):
 !           self.config.read(self.ini)
  !          if not self.config.has_section('general'):
   !             self.config.add_section('general')
    !            self.config.set('general', 'admin', "10")
     !           self.config.set('general', 'operator', "11")
      !          self.config.set('general', 'ban', "12")
       !         self.config.set('general', 'message', "Du bist geblockt.")
	!	 self.config.set('general', 'autoTalk', "True")
         !       self.config.set('general', 'autoOperator', "True")
          !      self.config.set('general', 'autoBan', "True")
	!		else:
	!			self.config['general'] = {"admin": "10", "operator": "11", "ban": "12", "message": "Du bist geblockt.", "autoTalk": "True", "autoOperator": "True", "autoBan": "True" }

    def stop(self):
        ts3lib.printMessageToCurrentTab("The userManager script has stopped! :(")

    def onNewChannelEvent(self, schid, channelID, channelParentID):
        err, name = ts3lib.getChannelVariableAsString(schid, channelID, ts3defines.ChannelProperties.CHANNEL_NAME)
        if err == ts3defines.ERROR_ok:
            ts3lib.printMessageToCurrentTab("new channel %s" % name)
        else:
            ts3lib.printMessageToCurrentTab("got error %s" % err)

**Comment by Bluscream** [comment]
```py
from ts3plugin import ts3plugin

import ts3lib, ts3defines
from os import path
from ts3plugin import ts3plugin

class userManager(ts3plugin):
name = "userManager"
requestAutoload = False
version = "1.0"
apiVersion = 21
author = "Simon"
description = "This is a testplugin"
offersConfigure = True
commandKeyword = "manager"
infoTitle = ""
menuItems = []
hotkeys = []
ini = path.join(ts3lib.getPluginPath(), "pyTSon", "scripts", "userManager", "cfg", "settings.ini")

def __init__(self):
    ts3lib.printMessageToCurrentTab("The userManager script is now running! :)")
	if path.isfile(self.ini):
        self.config.read(self.ini)
        if not self.config.has_section('general'):
            self.config.add_section('general')
            self.config.set('general', 'admin', "10")
            self.config.set('general', 'operator', "11")
            self.config.set('general', 'ban', "12")
            self.config.set('general', 'message', "Du bist geblockt.")
			self.config.set('general', 'autoTalk', "True")
            self.config.set('general', 'autoOperator', "True")
            self.config.set('general', 'autoBan', "True")
		else:
			self.config['general'] = {"admin": "10", "operator": "11", "ban": "12", "message": "Du bist geblockt.", "autoTalk": "True", "autoOperator": "True", "autoBan": "True" }

def stop(self):
    ts3lib.printMessageToCurrentTab("The userManager script has stopped! :(")

def onNewChannelEvent(self, schid, channelID, channelParentID):
    err, name = ts3lib.getChannelVariableAsString(schid, channelID, ts3defines.ChannelProperties.CHANNEL_NAME)
    if err == ts3defines.ERROR_ok:
        ts3lib.printMessageToCurrentTab("new channel %s" % name)
    else:
        ts3lib.printMessageToCurrentTab("got error %s" % err)
```

**Comment by Bluscream** [comment]
\```py
<dein code>
```

**Comment by GitSimonHub** [comment]
Es geht nicht ;/ 
https://www.file-upload.net/download-13181727/bluescreamhelp.zip.html

**Comment by Bluscream** [comment]
Pathmann hat schon recht, lies bitte https://www.quora.com/What-is-unexpected-indent-in-python
```
6/11/2018 01:13:47	pyTSon.PluginHost.reload	Error	Error loading python plugin from C:/Users/blusc/AppData/Roaming/TS3Client/plugins/pyTSon\scripts\userManager\: Traceback (most recent call last):
  File "C:/Users/blusc/AppData/Roaming/TS3Client/plugins/pyTSon/scripts\pluginhost.py", line 322, in reload
    cls.modules[base] = importlib.__import__(base)
  File "<frozen importlib._bootstrap>", line 1055, in __import__
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 767, in get_code
  File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:/Users/blusc/AppData/Roaming/TS3Client/plugins/pyTSon/scripts\userManager\__init__.py", line 8
    name = "userManager"
       ^
IndentationError: expected an indented block
```
