### ISSUE TITLE
Update python to 3.7.0

### ISSUE THREAD

**Issue by Bluscream** [pathmann/pyTSon#99]
Since [python 3.7.0](https://www.python.org/downloads/windows/) is the latest stable it would be nice if pytson would be updated to that python version.

Some of the notable changes include:
- PEP 539, new C API for thread-local storage
- PEP 545, Python documentation translations
- New documentation translations: Japanese, French, and Korean.
- PEP 552, Deterministic pyc files
- PEP 553, Built-in breakpoint()
- PEP 557, Data Classes
- PEP 560, Core support for typing module and generic types
- PEP 562, Customization of access to module attributes
- PEP 563, Postponed evaluation of annotations
- PEP 564, Time functions with nanosecond resolution
- PEP 565, Improved DeprecationWarning handling
- PEP 567, Context Variables
- **Avoiding the use of ASCII as a default text encoding (PEP 538, legacy C locale coercion and PEP 540, forced UTF-8 runtime mode)**
- The insertion-order preservation nature of dict objects is now an official part of the Python language spec.
- Notable performance improvements in many areas.
- PEP 468, Preserving Keyword Argument Order
- PEP 487, Simpler customization of class creation
- PEP 495, Local Time Disambiguation
- PEP 498, Literal String Formatting
- PEP 506, Adding A Secrets Module To The Standard Library
- PEP 509, Add a private version to dict
- PEP 515, Underscores in Numeric Literals
- PEP 519, Adding a file system path protocol
- PEP 520, Preserving Class Attribute Definition Order
- PEP 523, Adding a frame evaluation API to CPython
- PEP 524, Make os.urandom() blocking on Linux (during system startup)
- PEP 525, Asynchronous Generators (provisional)
- PEP 526, Syntax for Variable Annotations (provisional)
- PEP 528, **Change Windows console encoding to UTF-8**
- PEP 529, **Change Windows filesystem encoding to UTF-8**
- PEP 530, Asynchronous Comprehensions

Also pip that's being shipped is a few versions behind (latest is 3.1.10 if i remember correctly)

**Comment by pathmann** [comment]
Nice copy-paste, now explain, what features you miss.

**Comment by JF-Dunford** [comment]
> Nice copy-paste, now explain, what features you miss.
> Pip is updated in each bundle run.

It's not so much about what features we miss, as it is about being innovative and keeping up to date with technology. The latest Python version comes with performance improvements and new features. (In particular; but not limited to, PEP 567's new library modules for Context Variables and Data Classes.) It would be wonderful if my pyTSon projects could benefit from all this.

**Comment by pathmann** [comment]
I'm sorry, but this is not gonna happen (any time soon) from my side.

This project started as a fun project to build a Logitech G15 integration to the TeamSpeak client on linux and a fun project to mix python and C/C++.

Keeping track of every python release (and this would lead to it) would be a huge time and fun killer (for me!). 

Providing binaries for every available desktop platform is a must (in my opinion) but really no fun to me (setup or change build machines, build, test, adapt code, setup build machines, build ...).
See #87 for example. This did only involve two platforms (linux x86 and linux amd64), but it lasted nearly 3 months (sure, not 3 months of full work, this doesn't pay rent).

If you have time for that, feel free to provide a binary mirror with latest python builtin. If someone is willing to do so, I'd withdraw my uploads on myteamspeak.
